sonar-project.properties
Sonar currently showing very low coverage and test failure. It seems to suddenly be paying attention to the test/ directory
=> Ignore test directory in sonar

deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml, deploy/role.yaml, templates/multiclusterhub/base/apiserver/apiservice-clusterview_v1.yaml, templates/multiclusterhub/base/apiserver/apiservice-clusterview_v1alpha1.yaml, templates/multiclusterhub/base/apiserver/kustomization.yaml, templates/multiclusterhub/base/rbac/clusterrole-admin-aggregate.yaml, templates/multiclusterhub/base/rbac/clusterrole-clustermanageradmin-aggregate.yaml, templates/multiclusterhub/base/rbac/clusterrole-edit-aggregate.yaml, templates/multiclusterhub/base/rbac/clusterrole-foundation.yaml, templates/multiclusterhub/base/rbac/clusterrole-view-aggregate.yaml
add apiservice for the new aggregated api `clusterview.open-cluster-management.io`
story: https://github.com/open-cluster-management/backlog/issues/9691
task: https://github.com/open-cluster-management/backlog/issues/9694
=> add apiservice for clusterview api

pkg/controller/multiclusterhub/multiclusterhub_controller.go, pkg/imageoverrides/imageoverrides.go, pkg/utils/annotations.go, pkg/utils/annotations_test.go
https://github.com/open-cluster-management/backlog/issues/10422
=> Fix ImageRepository Overrides

pkg/controller/multiclusterhub/common_test.go, pkg/controller/multiclusterhub/multiclusterhub_controller.go, pkg/controller/multiclusterhub/status.go, pkg/controller/multiclusterhub/uninstall.go, pkg/controller/multiclusterhub/uninstall_test.go, pkg/subscription/cluster-lifecycle.go, pkg/subscription/subscription_test.go, test/multiclusterhub_install_test/multiclusterhub_test.go, test/multiclusterhub_update_test/multiclusterhub_test.go
Renaming rcm to cluster-lifecycle
=> 10050 add cluster lifecycle

deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml, deploy/role.yaml
fix issue : https://github.com/open-cluster-management/backlog/issues/10728
=> add deletion verb of apiservice to role

templates/multiclusterhub/base/webhook/webhook-mutating-config.yaml
story: https://github.com/open-cluster-management/backlog/issues/10443
=> upgrade ocm webhook adminssionReviewVersion to v1

.gitignore, Makefile, build/subscriptions/cluster-manager-op.yaml, deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml, deploy/role.yaml, pkg/webhook/validatingwebhook.go, test/Makefile, test/multiclusterhub_uninstall_test/multiclusterhub_test.go, test/resources/discoveryconfig.yaml, test/resources/observability-cr.yaml, test/resources/observability-crd.yaml, test/utils/utils.go
Also fixes observability functional test
https://github.com/open-cluster-management/backlog/issues/7206
=> Block Deletion of MCH if DiscoveyConfig Exists

pkg/controller/multiclusterhub/multiclusterhub_controller.go, pkg/controller/multiclusterhub/status.go, pkg/rendering/crd_renderer.go, pkg/rendering/crd_renderer_test.go, pkg/rendering/testdata/failure/bad.yaml, pkg/rendering/testdata/failure/policy.open-cluster-management.io_policies_crd.yaml, pkg/rendering/testdata/success/policy.open-cluster-management.io_policies_crd.yaml
User story: https://github.com/open-cluster-management/backlog/issues/9453
Update CRD renderer to return multiple errors. Display these errors in the multiclusterhub status so it's not necessary to dig through logs to find out why an install has stalled out.
=> Add hubcondition to status on failure to deploy CRDs

pkg/webhook/validatingwebhook.go
Resolves https://github.com/open-cluster-management/backlog/issues/11127
=> Check if APIs present in webhook delete validation

templates/multiclusterhub/base/rbac/clusterrole-view-aggregate.yaml
Related issue: https://github.com/open-cluster-management/backlog/issues/11243
=> Allow create & delete for managedclusterviews

deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml, deploy/role.yaml
Fixes for 
https://github.com/open-cluster-management/multicloudhub-operator/pull/545
https://github.com/open-cluster-management/multicloudhub-operator/pull/546
=> Add roles to roles.yaml

pkg/controller/multiclusterhub/common.go, pkg/controller/multiclusterhub/common_test.go, pkg/controller/multiclusterhub/multiclusterhub_controller.go, pkg/utils/utils.go
https://github.com/open-cluster-management/backlog/issues/10042
=> 10042 http proxy

Makefile, docs/configuration.md, pkg/controller/multiclusterhub/common.go, pkg/controller/multiclusterhub/multiclusterhub_controller.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/subscription/cluster-lifecycle.go, pkg/subscription/subscription.go, pkg/utils/annotations.go
https://github.com/open-cluster-management/backlog/issues/10506
Open Question before PR merge:  Is cluster lifecycle chart using imageSuffix?
=> remove image-tag-suffix

mock-component-image/scripts/generate-mock-charts.py, pkg/controller/multiclusterhub/common_test.go, pkg/controller/multiclusterhub/multiclusterhub_controller.go, pkg/controller/multiclusterhub/status.go, pkg/subscription/insights.go, pkg/subscription/subscription_test.go, test/utils/utils.go
=> insights chart changes 

mock-component-image/scripts/check_env_vars.py, mock-component-image/scripts/check_sha_env_var.py, mock-component-image/scripts/generate-helm-index.py, mock-component-image/scripts/generate-mock-charts.py, mock-component-image/scripts/generate-mock-foundation-binaries.sh, mock-component-image/scripts/generate-mock-image-manifest.py, mock-component-image/scripts/generate-mock-images.py, mock-component-image/templates/foundation-controller.go, mock-component-image/templates/foundation-proxyserver.go, mock-component-image/templates/foundation-webhook.go, pkg/controller/multiclusterhub/common.go
Fix warnings in Sonarcloud about 1 "bug" and 2 "vulnerabilities" by adding copyright headers and handling unhandled errors
=> Sonar fixes

pkg/controller/multiclusterhub/uninstall.go, pkg/controller/multiclusterhub/uninstall_test.go
https://github.com/open-cluster-management/backlog/issues/11115
=> Deleting the mirroredmanagedclusters CRD

deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml, deploy/role.yaml, templates/multiclusterhub/base/rbac/clusterrole-admin-aggregate.yaml, templates/multiclusterhub/base/rbac/clusterrole-edit-aggregate.yaml, templates/multiclusterhub/base/rbac/clusterrole-view-aggregate.yaml
Signed-off-by: Yu Cao <ycao@redhat.com>
=> add policyautomation permissions

deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml, deploy/role.yaml, templates/multiclusterhub/base/rbac/clusterrole-clustermanageradmin-aggregate.yaml
Signed-off-by: randybrunopiverger rbrunopi@redhat.com
@nathanweatherly
Regarding: https://github.com/open-cluster-management/backlog/issues/11596
=> hive permission addition

deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml, deploy/role.yaml, templates/multiclusterhub/base/rbac/clusterrole-clustermanageradmin-aggregate.yaml, templates/multiclusterhub/base/rbac/clusterrole-view-aggregate.yaml
**Related Issue** https://github.com/open-cluster-management/backlog/issues/11623 and https://github.com/open-cluster-management/backlog/issues/11644
- Backport PRs #545 and #546 to `release-2.1`
=> Allow create & delete for managedclusterviews and view pod/logs (release-2.1)

deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml, deploy/role.yaml, templates/multiclusterhub/base/rbac/clusterrole-admin-aggregate.yaml, templates/multiclusterhub/base/rbac/clusterrole-clustermanageradmin-aggregate.yaml, templates/multiclusterhub/base/rbac/clusterrole-edit-aggregate.yaml, templates/multiclusterhub/base/rbac/clusterrole-view-aggregate.yaml
Signed-off-by: Zack Layne <zlayne@redhat.com>
=> Add policyreport for get and list

go.mod, go.sum
Issue: https://github.com/open-cluster-management/backlog/issues/12569
=> Update dependency ulikunitz/xz to v0.5.10

templates/multiclusterhub/base/rbac/clusterrole-admin-aggregate.yaml
Signed-off-by: Hanqiu Zhang <hanzhang@redhat.com>
Issue: https://github.com/open-cluster-management/backlog/issues/13045
=> add create curator for admin role

.github/workflows/pr-function-tests.yml, Makefile, build/subscriptions/hive-op.yaml, build/subscriptions/subscription-op.yaml, common/scripts/pull-request-function-test.sh, common/scripts/update-image-manifest.sh, mock-component-image/scripts/generate-mock-charts.py, test/utils/resources.go, test/utils/utils.go
* Add PR Function Tests
* Update pr-function-tests.yml
https://github.com/open-cluster-management/backlog/issues/12973
=> Add PR Function Tests

pkg/webhook/setup.go
=>  changed to create or update

pkg/foundation/proxy_server.go
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
related issue: https://github.com/open-cluster-management/backlog/issues/13329
=> enabel ocm apiservice TLS

go.mod, go.sum, pkg/controller/multiclusterhub/common.go, pkg/controller/multiclusterhub/common_test.go, pkg/controller/multiclusterhub/multiclusterhub_controller_test.go, pkg/foundation/foundation.go, pkg/foundation/foundation_test.go
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
issue: https://github.com/open-cluster-management/backlog/issues/13489
=> fix that unable to update deployment/service/apiservice

mock-component-image/scripts/generate-mock-charts.py, pkg/controller/multiclusterhub/status.go, pkg/subscription/insights.go, test/utils/utils.go
https://github.com/open-cluster-management/insights-chart/pull/20
=> Rename insights to PolicyReport

.github/workflows/nightly-cron-function-tests.yml, Makefile, common/scripts/nightly-full-function-test.sh, common/scripts/slack-bot-message.sh, common/scripts/update-image-manifest.sh, test/multiclusterhub_install_test/multiclusterhub_test.go, test/multiclusterhub_uninstall_test/multiclusterhub_test.go, test/multiclusterhub_update_test/multiclusterhub_test.go, test/resources/discoveryconfig.yaml, test/utils/resources.go, test/utils/utils.go
Signed-off-by: Nathan Weatherly <nweather@redhat.com>
https://github.com/open-cluster-management/backlog/issues/12974
=> adding cron job for nightly function tests and slack bot to report

pkg/foundation/webhook.go
Issue: https://github.com/open-cluster-management/backlog/issues/13714
=> Set default mode in ocm webhook volume

go.sum, pkg/foundation/proxy_server.go, pkg/webhook/setup.go
Issue: https://github.com/open-cluster-management/backlog/issues/13878
Solution adapted from https://github.com/open-cluster-management/multiclusterhub-operator/pull/624
=> Cert rotate

.github/workflows/nightly-cron-function-tests.yml, Makefile, common/scripts/gather-crds.sh, common/scripts/slack-bot-message.sh, deploy/kustomization.yaml, test/multiclusterhub_install_test/multiclusterhub_test.go, test/utils/utils.go
https://github.com/open-cluster-management/backlog/issues/13713
=> Reconfigure funct tests

.github/workflows/pr-function-tests.yml, mock-component-image/Dockerfile, mock-component-image/scripts/generate-mock-foundation-binaries.sh, mock-component-image/templates/foundation-controller.go, mock-component-image/templates/resources/kustomization.yaml, mock-component-image/templates/resources/ocm-klusterlet-self-signed-secrets.yaml
=> Fix Mock PR Function tests

README.md
=> Re-trigger build

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, config/manager/manager.yaml
=> Update Container Name

controllers/managedcluster.go
Issue: https://github.com/open-cluster-management/backlog/issues/14190
=> Check namespace before creating managedcluster

pkg/controller/multiclusterhub/managedcluster.go
Issue: https://github.com/open-cluster-management/backlog/issues/14190
=> Check namespace before creating managedcluster (2.3)

README.md
=> Update doc links in readme

controllers/common_test.go, controllers/multiclusterhub_controller.go, pkg/subscription/cluster_proxy_addon.go, pkg/subscription/subscription_test.go, pkg/utils/utils.go, test/mock-component-image/scripts/generate-mock-charts.py
Issue: https://github.com/open-cluster-management/backlog/issues/15166
=> Add cluster proxy addon

pkg/foundation/foundation.go, pkg/foundation/foundation_test.go, pkg/foundation/proxy_server.go, pkg/foundation/webhook.go, pkg/helmrepo/helmrepo.go, pkg/helmrepo/helmrepo_test.go, pkg/utils/utils.go
Issue: https://github.com/open-cluster-management/backlog/issues/15623
Bringing forward fix for 2.3.2 https://github.com/open-cluster-management/multiclusterhub-operator/pull/650
=> Fix service selector and labels

pkg/subscription/cluster-lifecycle.go, pkg/subscription/discovery.go
Issue: https://github.com/open-cluster-management/backlog/issues/15624
=> Update subscription overrides

pkg/foundation/cluster_manager.go, pkg/foundation/cluster_manager_test.go
story: https://github.com/open-cluster-management/backlog/issues/15603
add nodeSelector and tolerations to clusterManager.
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
=> add nodeSelector and tolerations for ClusterManager

controllers/managedcluster.go
story: https://github.com/open-cluster-management/backlog/issues/15911
adding an annotation of nodeSelector to local-cluster managedCluster to support running pods on infra nodes.
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
=> sync nodeSelector to local managedcluster as annotation

controllers/multiclusterhub_controller.go, pkg/subscription/subscription_test.go, pkg/subscription/volsync.go, pkg/utils/utils.go, test/function_tests/utils/utils.go
=> Onboard volsync

bundle.Dockerfile, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/samples/operator_v1_multiclusterhub.yaml
https://github.com/open-cluster-management/backlog/issues/17920
=> Main - Update MCH Sample to remove Imagepullsecret

bundle.Dockerfile, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/samples/operator_v1_multiclusterhub.yaml
https://github.com/open-cluster-management/backlog/issues/17919
=> 2.4 - Update MCH Sample to remove Imagepullsecret

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, config/manager/manager.yaml, pkg/utils/utils.go, pkg/utils/utils_test.go, test/function_tests/multiclusterhub_install_test/multiclusterhub_test.go, test/function_tests/utils/utils.go
=>  change to if not present

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, config/manager/manager.yaml, hack/subscriptions/hive-operator.yaml, hack/subscriptions/subscription-operator.yaml, pkg/utils/utils.go, pkg/utils/utils_test.go, test/function_tests/multiclusterhub_install_test/multiclusterhub_test.go, test/function_tests/utils/utils.go
=> change to if not always

build/index-install/composite/deploy.yaml, build/index-install/non-composite/deploy.yaml, deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml, deploy/operator.yaml, pkg/utils/utils.go, pkg/utils/utils_test.go, test/multiclusterhub_install_test/multiclusterhub_test.go, test/utils/utils.go
=>  change pull policy to if not present

.github/workflows/nightly-cron-function-tests.yml, .github/workflows/pr-function-tests.yml, CONTRIBUTING.md, build/Dockerfile.prow, build/Dockerfile.test.prow, docs/installation.md, go.mod
=> Update Go version to 1.17 [2.3]

README.md
No-op PR to fix changes not propogating in prow build
=> Retrigger build

README.md
=> Retrigger 2.3.6 build

api/v1/multiclusterhub_types.go, bundle.Dockerfile, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manifests/bases/multiclusterhub-operator.clusterserviceversion.yaml
/hold
https://github.com/open-cluster-management/backlog/issues/17765
Awaiting Approval
Updates xDescriptors for boolean fields to match - https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#3-k8sResourcePrefix
=> Fix xDescriptors

api/v1/multiclusterhub_types.go, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/multiclusterhub-operator.clusterserviceversion.yaml
https://github.com/open-cluster-management/backlog/issues/17765
=> Fix xDescriptors (2.4)

README.md, controllers/finalizers.go, controllers/status.go, pkg/multiclusterengine/multiclusterengine.go, pkg/multiclusterengine/multiclusterengine_test.go, pkg/utils/annotations.go, pkg/utils/utils.go
https://github.com/open-cluster-management/backlog/issues/18088
/hold
=> Override MultiClusterEngine subscription

pkg/multiclusterengine/multiclusterengine.go, pkg/multiclusterengine/multiclusterengine_test.go
https://github.com/open-cluster-management/backlog/issues/18536
=> Update MCE channel

pkg/rendering/renderer.go
=> Fix org rename

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/common.go, controllers/multiclusterhub_controller.go, controllers/uninstall.go, controllers/uninstall_test.go, pkg/webhook/setup.go
/hold
https://github.com/stolostron/backlog/issues/19185
=> Enable upgrade to 2.5

controllers/common.go
=> Bug fix - Allow for MCE CRD not to exist at runtime

controllers/common.go, controllers/finalizers.go, controllers/multiclusterhub_controller_test.go, pkg/multiclusterengine/multiclusterengine.go, pkg/multiclusterengine/multiclusterengine_test.go, pkg/utils/utils.go, test/function_tests/multiclusterhub_install_test/multiclusterhub_test.go, test/function_tests/utils/utils.go
Issue: https://github.com/stolostron/backlog/issues/18901
=>  subscription propagation

controllers/common.go, controllers/finalizers.go, controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go, controllers/status.go, controllers/suite_test.go, go.mod, go.sum, main.go, pkg/multiclusterengine/multiclusterengine.go, pkg/utils/utils.go, test/unit-tests/resources.go
https://github.com/stolostron/backlog/issues/18903
=> Allow preexisting MCE

README.md
Signed-off-by: Nathan Weatherly nweather@redhat.com
=> no op change

controllers/uninstall.go
Issue: https://github.com/stolostron/backlog/issues/19853
=> Revert velero CRD removal

controllers/common.go, controllers/multiclusterhub_controller_test.go, pkg/multiclusterengine/multiclusterengine.go
https://github.com/stolostron/backlog/issues/20064
https://github.com/stolostron/backlog/issues/20342
=> Ensure NodeSelector and Supported Annotations

docs/disconnected-install-aws.md
=> add disconnected install example

controllers/multiclusterhub_controller.go, pkg/subscription/volsync.go, pkg/utils/utils.go
=>  onboard volsync

api/v1/multiclusterhub_methods.go, controllers/finalizers.go, pkg/utils/utils.go, test/function_tests/multiclusterhub_install_test/multiclusterhub_test.go, test/unit-tests/resources.go
https://github.com/stolostron/backlog/issues/19626
=> Ns namechange

controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Issue: https://github.com/stolostron/backlog/issues/20901
=> Deduplicate component spec and remove EnableClusterProxyAddon ref

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/multiclusterhub_controller.go, pkg/webhook/validatingwebhook.go
Issue: https://github.com/stolostron/backlog/issues/20380
=> Require no AgentServiceConfigs to delete MCH

controllers/common.go, go.mod, go.sum
Issue: https://github.com/stolostron/backlog/issues/21016
=> Set InfrastructureCustomNamespace on new MCE if AI configured

api/v1/multiclusterhub_methods.go
https://github.com/stolostron/backlog/issues/21050
=>  disabled cluster backup

controllers/status.go
=> Type added for MCE sub/csv status in MCH specs

controllers/common.go
https://github.com/stolostron/backlog/issues/21278
=>  add conditional

README.md, pkg/subscription/cluster_backup.go, pkg/subscription/subscription.go, pkg/subscription/subscription_test.go, pkg/utils/annotations.go
Issue: https://github.com/stolostron/backlog/issues/21583
=> Oadp override annotation

controllers/common.go, controllers/multiclusterhub_controller.go
Issue: https://github.com/stolostron/backlog/issues/21586
=> Update Velero CRDs rather than delete

controllers/common.go, controllers/multiclusterhub_controller.go
Issue: https://github.com/stolostron/backlog/issues/21579
=> check for pullsecret when installing mch

controllers/multiclusterhub_controller.go
=> check for an error when setting ACM_HUB_OCP_VERSION environment variable

controllers/common.go, controllers/multiclusterhub_controller.go
Issue: https://github.com/stolostron/backlog/issues/21579
=> check for pullsecret when installing mch in acm 2.4

README.md
Issue: https://github.com/stolostron/backlog/issues/22154
=> [release-2.2] trigger rebuild

pkg/helmrepo/helmrepo.go, pkg/utils/utils.go
=> Use emptyDir volume in helrepo deployment

pkg/multiclusterengine/multiclusterengine.go, pkg/multiclusterengine/multiclusterengine_test.go, test/function_tests/utils/resources.go
=>  update MCE channel 2.1

Dockerfile, build/Dockerfile.prow, build/Dockerfile.test.prow, go.mod
=> update release-2.5 branch to go 1.18

build/Dockerfile.prow, build/Dockerfile.test, build/Dockerfile.test.prow, go.mod
=> update release-2.3 branch to go 1.18

Dockerfile, build/Dockerfile.prow, build/Dockerfile.test.prow, go.mod
=> update release-2.4 branch to go 1.18

controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go
=> create ocm cluster-wide proxy configmap

api/v1/methods_test.go, api/v1/multiclusterhub_methods.go, controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, pkg/webhook/validatingwebhook.go
=> 21967 search community operator mode

controllers/multiclusterhub_controller.go
Issue: https://github.com/stolostron/backlog/issues/24446
=> Add predicates to deployment watches

controllers/status_test.go
=> Add unit tests for status functions

controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
=> Uncomment search-v2 render

api/v1/methods_test.go, api/v1/multiclusterhub_methods.go, pkg/utils/utils.go
=>  temporarily remove search-v2

controllers/multiclusterhub_controller.go
Issue: https://github.com/stolostron/backlog/issues/24782
=> sync mce version with acm

controllers/multiclusterhub_controller.go
=> fix upgrade mce in 2.6

pkg/rendering/renderer.go, pkg/rendering/renderer_test.go
issue: https://github.com/stolostron/backlog/issues/24856
=> tolerations fix

controllers/multiclusterhub_controller.go
Issue: https://github.com/stolostron/backlog/issues/25587
=> Ensure CLC and search are cleaned up before deleting MCH

pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-controller-manager.yaml
Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>
=>  updated search limit memory

controllers/common.go, controllers/managedcluster.go, controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go, controllers/status.go, controllers/status_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
issue: https://github.com/stolostron/backlog/issues/25560
=> handle ocp console disabled scenario

controllers/common.go
Issue: https://github.com/stolostron/backlog/issues/26116
=> Update MCE sub list and label handling

pkg/templates/charts/toggle/grc/templates/grc-policy-addon-deployment.yaml, pkg/templates/charts/toggle/grc/values.yaml, pkg/utils/utils.go
Refs:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/25
- https://github.com/stolostron/backlog/issues/26297
- https://github.com/stolostron/backlog/issues/26298
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>
=> Use consolidated controller

pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-clusterrole.yaml, pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-controller-manager.yaml, pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-role.yaml
Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>
=> move search watch to namespace scope

pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml, test/unit-tests/crds/policy.yaml
Refs:
- https://github.com/stolostron/backlog/issues/26187
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>
=> Update Policy CRD

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml, pkg/templates/charts/toggle/cluster-backup/templates/placement-binding.yaml, pkg/templates/charts/toggle/cluster-backup/templates/placement-rule.yaml, test/unit-tests/crds/placementbinding.yaml, test/unit-tests/crds/placementrule.yaml
https://github.com/stolostron/backlog/issues/26284
=>  split up hub backup pod

pkg/templates/crds/grc/policy.open-cluster-management.io_policyautomations.yaml
Signed-off-by: Chunxi Luo <chuluo@redhat.com>
=> add policyViolationContextLimit into PolicyAutomation

pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_restores.yaml
Signed-off-by: sahare <sahare@redhat.com>
https://issues.redhat.com/browse/ACM-1890
=> Update restore CRD

pkg/templates/charts/toggle/grc/templates/grc-clusterrole.yaml
Relates:
https://github.com/stolostron/backlog/issues/25849
https://issues.redhat.com/browse/ACM-1911
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
=> Grant the Policy Propagator watch access

pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml
Signed-off-by: Will Kutler <wkutler@redhat.com>
=> add pending to compliance enum

api/v1/v1_suite_test.go, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/multiclusterhub_controller.go, controllers/suite_test.go, main.go, pkg/rendering/renderer.go, pkg/templates/crds/grc/OWNERS, test/function_tests/utils/utils.go
Issue: https://github.com/stolostron/backlog/issues/26629
=> Stop installing CRDs from hub-crds injection

pkg/templates/crds/grc/policy.open-cluster-management.io_policyautomations.yaml
Signed-off-by: Chunxi Luo <chuluo@redhat.com>
=> update policyViolationContextLimit description

.github/workflows/nightly-cron-function-tests.yml, .github/workflows/pr-function-tests.yml, Dockerfile, build/Dockerfile.prow, build/Dockerfile.test.prow, go.mod
=> update to go 1.19

main.go, pkg/webhook/setup.go
Issue: https://github.com/stolostron/backlog/issues/26672
=> Configure TLS minimum version to 1.2

pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-role.yaml
Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>
=>  added pods to role

controllers/common.go
=> Requeue if MCE not ready

controllers/multiclusterhub_controller.go
=> mch console fix

controllers/common.go, controllers/managedcluster.go, controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go, controllers/status.go, controllers/status_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
issue: https://github.com/stolostron/backlog/issues/25561
=> handle ocp console disabled scenario [2.6]

pkg/templates/crds/cluster-backup/velero.io_restores.yaml
Signed-off-by: Valentina Birsan <vbirsan@redhat.com>
https://github.com/stolostron/backlog/issues/25725
=> update velero crds to v1.9.1

README.md, controllers/common.go, controllers/multiclusterhub_controller.go, controllers/status.go, pkg/utils/annotations.go, pkg/utils/annotations_test.go, pkg/version/version.go, pkg/version/version_test.go
Issue: https://github.com/stolostron/backlog/issues/26481
=> Report not progressing when in unsupported OCP env

controllers/multiclusterhub_controller.go
=>  app sub regression fix

pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml, test/unit-tests/crds/policy.yaml
Refs:
- https://github.com/open-cluster-management-io/governance-policy-propagator/pull/73
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>
=> Sync policy CRD

controllers/common.go, controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go, test/unit-tests/crds/console-operator.yaml
Jira issue: https://issues.redhat.com/browse/ACM-2116
=> Move console plugin

pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-clusterrole.yaml
Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>
Adding role to get Nodelselector and Toleration from AddonDeplymentConfig.
=> added role for addondeploymentconfigs create

pkg/templates/charts/toggle/console/templates/console-clusterrole.yaml
Follow-up for https://github.com/stolostron/console/pull/2304
=> Grant permissions for storageclass, agentserviceconfigs and clusterversions

pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-applications-clustermanagementaddon.yaml
Signed-off-by: Philip Wu <phwu@redhat.com>
=> Add clustermanagementaddon for app LC

controllers/finalizers.go, controllers/multiclusterhub_controller.go
Issue: https://github.com/stolostron/backlog/issues/26989
Ignores apinotfound error when deleting a resource or finaling. Also moves image reading to before finalizer code.
=> Ignore API not found errors on delete and finalize

api/v1/multiclusterhub_types.go, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml, config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml, config/manifests/bases/multiclusterhub-operator.clusterserviceversion.yaml
=> custom ca configmap deprecation

pkg/multiclusterengine/multiclusterengine.go, pkg/multiclusterengine/subscription.go
=> Search packagemanifests with variable desired package name

bundle.Dockerfile, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml, bundle/metadata/annotations.yaml, config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml, config/manifests/bases/multiclusterhub-operator.clusterserviceversion.yaml, controllers/common.go, pkg/version/version.go, pkg/version/version_test.go
=> Require MCE version based on whether community mode

controllers/common.go, main.go
=> jira 2273: fix crashloop for 3000 clusters

controllers/common.go
Jira: https://issues.redhat.com/browse/ACM-2448
=> Update Search CR when MCH is updated

controllers/multiclusterhub_controller.go, controllers/uninstall.go
Deploy appsub component earlier to finalize helmreleases and wait for cleanup to complete before deploying new resources.
OADP csv must also manually be deleted because the helmrelease cleanup only removes the subscription it deployed.
Relates to Jiras ACM-2465 and ACM-2259
=> Wait for helmrelease cleanup before deploying new resources

pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml
Signed-off-by: Will Kutler <wkutler@redhat.com>
refs:
- https://issues.redhat.com/browse/ACM-2021?filter=-1
=> add enum for compliance in policy dependency crd

pkg/templates/crds/grc/OWNERS, pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml, test/unit-tests/crds/policy.yaml
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
=> `PolicyDepenency` --> `PolicyDependency`

pkg/templates/multiclusterhub/base/clusterrole-admin-aggregate.yaml, pkg/templates/multiclusterhub/base/clusterrole-edit-aggregate.yaml, pkg/templates/multiclusterhub/base/clusterrole-view-aggregate.yaml
Signed-off-by: Maggie Chen <magchen@redhat.com>
https://issues.redhat.com/browse/ACM-2912
=> Add  subscriptionstatuses and subscriptionreports

pkg/templates/crds/grc/policy.open-cluster-management.io_policyautomations.yaml
Relates:
https://issues.redhat.com/browse/ACM-2946
https://github.com/stolostron/governance-policy-propagator/pull/321
=> Update the CRD to match a renamed Policy field

hack/bundle-automation/config.yaml, hack/scripts/dev-update-image-references.py, hack/scripts/generate_images.py, pkg/multiclusterengine/multiclusterengine.go, pkg/version/version.go, test/function_tests/utils/resources.go
=> channel update

pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml
Relates:
https://issues.redhat.com/browse/ACM-1690
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
=> Add the Policy spec.copyPolicyMetadata field

pkg/templates/charts/toggle/insights/templates/policyreport-metrics-deployment.yaml
Fix for https://issues.redhat.com/browse/ACM-3295
=> remove TLS cipher TLS_RSA_WITH_3DES_EDE_CBC_SHA

pkg/templates/charts/toggle/console/templates/console-userpreference-clusterrole.yaml
Related bug: https://issues.redhat.com/browse/ACM-3917
=> Add UserPreference clusterrole

pkg/templates/multiclusterhub/base/clusterrole-admin-aggregate.yaml, pkg/templates/multiclusterhub/base/clusterrole-edit-aggregate.yaml, pkg/templates/multiclusterhub/base/clusterrole-view-aggregate.yaml, pkg/templates/multiclusterhub/base/multicluster-applications-rbac-aggregate-admin.yaml, pkg/templates/multiclusterhub/base/multicluster-applications-rbac-aggregate-edit.yaml, pkg/templates/multiclusterhub/base/multicluster-applications-rbac-aggregate-view.yaml
https://issues.redhat.com/browse/ACM-1301
=> Add permission for the new multiclusterappsetreport

pkg/templates/charts/toggle/console/templates/console-clusterrole.yaml
=> Give console service account get auth for userpreference

pkg/templates/crds/search-v2-operator/search.open-cluster-management.io_searches.yaml
issue: https://issues.redhat.com/browse/ACM-4116
=> ACM-4116 Edit Seach V2 descriptors

controllers/uninstall.go
issue: https://issues.redhat.com/browse/ACM-4120
=> ACM-4120 Remove Search V1 CRDs from 2.8

.github/workflows/nightly-cron-function-tests.yml, .github/workflows/pr-function-tests.yml, Dockerfile, build/Dockerfile.prow, build/Dockerfile.test.prow, bundle.Dockerfile, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml, bundle/metadata/annotations.yaml, config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml, config/rbac/role.yaml, config/webhook/manifests.yaml, go.mod
Jira: https://issues.redhat.com/browse/ACM-1770
=> [release-2.6] Update Go to 1.20

.github/workflows/nightly-cron-function-tests.yml, .github/workflows/pr-function-tests.yml, Dockerfile, build/Dockerfile.prow, build/Dockerfile.test.prow, bundle.Dockerfile, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, go.mod
Jira: https://issues.redhat.com/browse/ACM-1787
=> [release-2.7] Update Go to 1.20

main.go
Issue: https://issues.redhat.com/browse/ACM-4453
=> ACM-4453 Implement Leader Collection

hack/bundle-automation/generate-bundles.py
I believe the value should be changed to CustomResourceDefinition in the addCrd function instead of ClusterManagementAddon
also added some comments to help explain some logic more
=> fixing logic to correctly find crds to add

api/v1/multiclusterhub_methods.go, api/v1/multiclusterhub_types.go, controllers/common.go, controllers/hosted.go, controllers/multiclusterhub_controller.go, pkg/multiclusterengine/hosted.go, pkg/multiclusterengine/multiclusterengine.go, pkg/utils/annotations.go, pkg/utils/utils.go, pkg/webhook/validatingwebhook.go
Jira: https://issues.redhat.com/browse/ACM-3283
Scope is limited to just setting up the MCE in hosted mode, and supporting more than one MCE or MCH. Most of the code is contained within the `hosted.go` files to minimize affecting the main code paths.
=> ACM-3283 : Introduce Hosted Mode

.github/workflows/regenerate-bundles-2.7.yml, .github/workflows/update-crds-2.5.yml, .github/workflows/update-crds-2.6.yml
Jira: https://issues.redhat.com/browse/ACM-4522
=> ACM-4522 : Regenerate bundles for previous MCH versions

pkg/templates/charts/toggle/grc/OWNERS, pkg/templates/crds/grc/OWNERS
Team changes so updating the owners files
=> Update the owners file due to team changes

main.go
issue: https://issues.redhat.com/browse/ACM-4458
=> ACM-4458 Reduce cache usage by default in MCH

hack/bundle-automation/generate-bundles.py
Signed-off-by: Erin Murphy erinmurp@redhat.com
=> [2.7] Add ClusterManagementAddon resources in bundle automation

hack/bundle-automation/generate-bundles.py
Signed-off-by: Erin Murphy erinmurp@redhat.com
=> [2.6] Add ClusterManagementAddon resources in bundle automation

pkg/templates/multiclusterhub/base/clusterrole-admin-aggregate.yaml, pkg/templates/multiclusterhub/base/clusterrole-edit-aggregate.yaml, pkg/templates/multiclusterhub/base/clusterrole-view-aggregate.yaml
https://issues.redhat.com/browse/ACM-5271
=> ACM-5271: Add argocds for subscription RBAC user

main.go, pkg/webhook/setup.go
Jira: https://issues.redhat.com/browse/ACM-5226
=> Update webhook server tls min version to 1.3

controllers/managedcluster.go
Jira: https://issues.redhat.com/browse/ACM-5330
=> ACM-5330: Remove KlusterletAddonConfig deprecated fields

main.go
Jira: https://issues.redhat.com/browse/ACM-4585
=> ACM-4585: Allow operator upgrade when no MCH's present

main.go
issue: https://issues.redhat.com/browse/ACM-5508
=> ACM-5508 Change Logger Timestamp

pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-integrations.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-application.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-subscription-report.yaml
Reverts https://github.com/stolostron/multiclusterhub-operator/pull/1034
=> Revert changes to seccompProfile preventing deploy

.github/workflows/regenerate-bundles-2.8.yml, hack/bundle-automation/config.yaml, hack/prereqs/oc.yaml, hack/scripts/dev-update-image-references.py, hack/scripts/generate_images.py, pkg/multiclusterengine/multiclusterengine.go, pkg/version/version.go, test/function_tests/utils/resources.go
Signed-off-by: Erin Murphy erinmurp@redhat.com
issue: https://issues.redhat.com/browse/ACM-5609
=> Setup MCH 2.9

controllers/common.go
Jira: https://issues.redhat.com/browse/ACM-5399
=> ACM-5399: Use update instead of SSA for MCE subscription

hack/bundle-automation/generate-bundles.py
This  PR is the MCH-operator twin of  stolostron/backplane-operator#450 and makes this repo's `generate-bundle.py` identical to the one in backplane-operator as of this date.    Resyncing the two copies of the script not only picks up the desired changes for addressing seccompprofile warnings, it also makes it easier to maintain the two copies moving foward.  (Some drift had occurred, in that this repo's copy was missing some optional enhancements needed for Hive and done in the copy in backplane-operator).
=> Address secompprofile warnings in bundle-originated charts

pkg/templates/crds/grc/policy.open-cluster-management.io_placementbindings.yaml
ref: https://issues.redhat.com/browse/ACM-1397
=> Sync PlacementBinding for selective enforcement

pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-deployment.yaml, pkg/templates/charts/toggle/insights/templates/policyreport-metrics-deployment.yaml
- policyreport-metrics-deployment.yaml
- Reverts PR: https://github.com/stolostron/multiclusterhub-operator/pull/980
- grc-policy-propagator-deplayment.yaml
=> Min TLS version 1.2

pkg/rendering/renderer_test.go, pkg/templates/charts/toggle/volsync-controller/templates/volsync-addon-controller-deployment.yaml
Jira: https://issues.redhat.com/browse/ACM-6192
=> ACM-6192: Fix volsync deployment spacing

controllers/multiclusterhub_controller.go
Jira: https://issues.redhat.com/browse/ACM-6550
=> ACM-6550: Remove configmap watch to reduce cache demands

Dockerfile, api/v1/methods_test.go, api/v1/multiclusterhub_methods.go, controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go, hack/bundle-automation/config.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/Chart.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/templates/manager-config_v1_configmap.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator-clusterrole.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator-clusterrolebinding.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator-serviceaccount.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-webhook-service_v1_service.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/values.yaml, pkg/templates/crds/multicluster-observability-operator/core.observatorium.io_observatoria.yaml, pkg/templates/crds/multicluster-observability-operator/observability.open-cluster-management.io_multiclusterobservabilities.yaml, pkg/templates/crds/multicluster-observability-operator/observability.open-cluster-management.io_observabilityaddons.yaml, pkg/utils/utils.go, pkg/utils/utils_test.go, test/unit-tests/resources.go
Migrating Observability to be deployed by the MCH operator and not OLM.
=> [ACM-6677] Migrated Observability out of ACM bundle

pkg/rendering/renderer.go, pkg/rendering/renderer_test.go, pkg/templates/charts/toggle/cluster-backup/values.yaml, pkg/templates/crds/cluster-backup/velero.io_backups.yaml, pkg/templates/crds/cluster-backup/velero.io_restores.yaml, pkg/templates/crds/cluster-backup/velero.io_schedules.yaml
This reverts commit 10d8cc7ba7415fc972f9fe02dcfc06ebeb9f8b38.
Fixing https://issues.redhat.com/browse/ACM-6997
=> Revert "Update Velero CRDs and upgrade to OADP 1.2 channel (#1066)"

OWNERS
Updated OWNERS to match source of truth.
=> [Automated PR] Resynced OWNERS file for main

pkg/templates/charts/toggle/submariner-addon/templates/submariner-addon-clusterrole.yaml
Updating `submariner-addon` chart template.
https://issues.redhat.com/browse/ACM-7574
Updated submariner-addon chart template to reflect the change for the clusterrole to include the `update` permission for `clustermanagementaddons`.
=> [ACM-7574] Updated submariner chart

.github/workflows/regenerate-bundles-2.7.yml, .github/workflows/regenerate-bundles-2.8.yml, .github/workflows/regenerate-bundles.yml, .github/workflows/update-pregenerated-charts.yml
Updating Github Actions to send slack notification if job fails.
N/A
Updated Github Action to alert team if failure occured.
N/A
=> Updated github action workflow to send failure to slack

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, config/manager/manager.yaml
=> SCC V2 privilaged and ro root filesystem

pkg/templates/charts/toggle/console/templates/console-servicemonitor.yaml
Use `{{ .Values.global.namespace }}` to set the namespace selector in Console ServiceMonitor
https://issues.redhat.com/browse/ACM-8366
Updated namespace selector to be set using: `{{ .Values.global.namespace }}`
=> ACM-8366 Fix namespace selector for console ServiceMonitor

pkg/multiclusterengine/multiclusterengine.go, pkg/version/version.go, test/function_tests/utils/resources.go
Updating MCE version to 2.5 for ACM 2.10.
https://issues.redhat.com/browse/ACM-8974
Updated the required version and channel for MCE to use 2.5.
=> [ACM-8974] Updated MCE required version to 2.5

pkg/templates/charts/toggle/console/templates/console-clusterrole.yaml
Removes unneeded permissions for console deployment
https://issues.redhat.com/browse/ACM-9150
- Remove argoproj.io/appprojects and organize by API group
- Sync with backplane-operator version
/cc @JakobGray @fxiang1
=> ACM-9150 Reduce permissions for console deployment

hack/bundle-automation/chart-templates/Chart.yaml, hack/bundle-automation/config.yaml, hack/bundle-automation/copy-config.yaml, hack/prereqs/oc.yaml, hack/scripts/dev-update-image-references.py, hack/scripts/generate_images.py, pkg/templates/charts/toggle/cluster-backup/Chart.yaml, pkg/templates/charts/toggle/cluster-lifecycle/Chart.yaml, pkg/templates/charts/toggle/cluster-permission/Chart.yaml, pkg/templates/charts/toggle/console/Chart.yaml, pkg/templates/charts/toggle/grc/Chart.yaml, pkg/templates/charts/toggle/insights/Chart.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/Chart.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/Chart.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator.yaml, pkg/templates/charts/toggle/search-v2-operator/Chart.yaml, pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-clusterrole.yaml, pkg/templates/charts/toggle/submariner-addon/Chart.yaml, pkg/templates/charts/toggle/volsync-controller/Chart.yaml, pkg/templates/crds/multicluster-observability-operator/observability.open-cluster-management.io_multiclusterobservabilities.yaml, pkg/templates/crds/multicluster-observability-operator/observability.open-cluster-management.io_observabilityaddons.yaml
Updated config files to use the current release version for ACM 2.10.
https://issues.redhat.com/browse/ACM-8309
Updated bundle-automation config to point to `release-2.10` branches.
Updated component templates `Chart.yaml` files to use version `2.10.0`.
=> [ACM-8309] Updated bundle-automation config to use release-2.10

hack/bundle-automation/config.yaml, hack/bundle-automation/generate-shell.py
Added the config file back for bundle generation and updated the wrapper script accordingly
https://issues.redhat.com/browse/ACM-8296
=> bundle generation move with config

.github/workflows/regenerate-bundles-2.7.yml, .github/workflows/regenerate-bundles-2.8.yml, .github/workflows/regenerate-bundles-2.9.yml, .github/workflows/regenerate-bundles.yml, .github/workflows/update-pregenerated-charts.yml
Added `release-2.9` regenerate-bundle Github action job.
Added `release-2.9` regenerate-bundle Github action job.
=> Added GH action for release-2.9

controllers/multiclusterhub_controller.go, pkg/rendering/renderer.go, pkg/rendering/renderer_test.go
Related Jira Issue: https://issues.redhat.com/browse/ACM-9282
=> add namespace to CRD rendering

api/v1/multiclusterhub_methods.go
Adding `image-based-install-operator` to MCE component list.
https://issues.redhat.com/browse/ACM-8430
Updated MCE component list to include latest component.
/cc @cameronmwall @ngraham20 
/hold
=> [ACM-8430] Added MCE ibio component

hack/bundle-automation/chart-templates/values.yaml, pkg/templates/charts/toggle/cluster-backup/values.yaml, pkg/templates/charts/toggle/cluster-lifecycle/values.yaml, pkg/templates/charts/toggle/cluster-permission/values.yaml, pkg/templates/charts/toggle/grc/values.yaml, pkg/templates/charts/toggle/insights/values.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/values.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/values.yaml, pkg/templates/charts/toggle/search-v2-operator/templates/search-collector.clustermanagementaddon.yaml, pkg/templates/charts/toggle/search-v2-operator/values.yaml, pkg/templates/charts/toggle/submariner-addon/values.yaml, pkg/templates/charts/toggle/volsync-controller/values.yaml
Some of our tests are reporting template evaluation errors on Helm flow-control expressions regarding a semver test.  This is because the values.yaml being used for the tests either lacks a definition for Values.hubconfig.ocpVersion, or the value is a null string which isn't valid for such a test.  This PR should fix these.
- Adjust values.yaml files to add proper definition of Values.hubconfig.ocpVersion (using 4.12.0).
- Add null map for Values.templateOverrides to prepare for use of those overrides.
=> Fix template evaluation errors in PR tests

hack/bundle-automation/requirements.txt
Updating the bundle-automation `requirements.txt` file to be the same as MCE.
Updated `hack/bundle-automation/requirements.txt`.
=> Syncing requirements.txt to MCE requirements

.github/workflows/regenerate-bundles-2.10.yml, .github/workflows/regenerate-bundles-2.7.yml, .github/workflows/regenerate-bundles-2.8.yml, .github/workflows/regenerate-bundles.yml, .github/workflows/update-pregenerated-charts.yml
Updating Github Action to support release updates for `release-2.10`.
https://issues.redhat.com/browse/ACM-10239
Added Github Action file for `release-2.10`.
/cc @cameronmwall @joeg-pro
=> [ACM-10239] Updated Github action scripts

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-auto-import.yaml
authentication.open-cluster-management.io/v1alpha1 ManagedServiceAccount is deprecated; use authentication.open-cluster-management.io/v1beta1 ManagedServiceAccount
https://issues.redhat.com/browse/ACM-10214
Use authentication.open-cluster-management.io/v1beta1 ManagedServiceAccount
=> Update ManagedServiceAccount API version to v1beta1

api/v1/multiclusterhub_types.go, config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml, docs/available-components.md
description change
https://issues.redhat.com/browse/ACM-8981
https://issues.redhat.com/browse/ACM-9483
=>  add more API description

controllers/multiclusterhub_controller.go
Added a warning log to indicate that a deprecated field is being used with the MCH CR spec.
https://issues.redhat.com/browse/ACM-10271
Added additional logging to check if deprecated fields are being used within MCH.
=> [ACM-10271] Added warning logs for deprecated spec field usage

pkg/multiclusterengine/multiclusterengine.go, pkg/version/version.go
Updated MCE community operator version to correct version.
Updated MCE community operator version.
=> [release-2.8] Updated MCE community channel version

pkg/multiclusterengine/multiclusterengine.go, pkg/version/version.go
Updated MCE community operator version to correct version.
Updated MCE community operator version.
=> [release-2.10] Update MCE community channel version

pkg/multiclusterengine/multiclusterengine.go, pkg/version/version.go
Updated MCE community operator version to correct version.
Updated MCE community operator version.
=> [release-2.9] Update MCE community channel version

api/v1/multiclusterhub_methods.go, api/v1/webhook_suite_test.go, controllers/common.go, controllers/finalizers.go, controllers/managedcluster.go, controllers/status.go, main.go, pkg/multiclusterengine/multiclusterengine_test.go, test/function_tests/multiclusterhub_install_test/multiclusterhub_operator_suite_test.go, test/function_tests/multiclusterhub_uninstall_test/multiclusterhub_operator_suite_test.go, test/function_tests/multiclusterhub_update_test/multiclusterhub_operator_suite_test.go
Removing unreferenced code from the repository to resolve code repository smells.
https://issues.redhat.com/browse/ACM-8209
Remove unused code from repository.
=> [ACM-8209] Removed unused code in repo

hack/bundle-automation/config.yaml, hack/bundle-automation/copy-config.yaml
Updated `bundle-automation/config.yaml` to use current release branch ref.
Updated the `bundle-automation/config.yaml` to use `release-2.11` branch ref.
=> Updated config.yaml to use 2.11 branch reference

pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-integrations.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-application.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-channel.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-hub-subscription.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-standalone-subscription.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-subscription-report.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator.yaml, pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-controller-manager.yaml, pkg/templates/charts/toggle/submariner-addon/templates/submariner-addon.yaml
Reverts stolostron/multiclusterhub-operator#1396
=> Revert "Operator Bundle Update"

api/v1/multiclusterhub_methods.go, api/v1/multiclusterhub_methods_test.go, api/v1/multiclusterhub_types.go, config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml
=> Hubsize property

pkg/templates/crds/grc/policy.open-cluster-management.io_placementbindings.yaml, pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml, pkg/templates/crds/grc/policy.open-cluster-management.io_policyautomations.yaml, pkg/templates/crds/grc/policy.open-cluster-management.io_policysets.yaml
Sync GRC CRD description updates.
https://issues.redhat.com/browse/ACM-8976
=> Sync GRC CRDs

Makefile
Updating the `Makefile` controller-runtime `envtest` package version.
Updated version from `latest` to `release-0.17`.
=> Updated Makefile to support compatible controller-runtime envtest

.gitignore, api/v1/multiclusterhub_types.go, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, hack/bundle-automation/chart-templates/values.yaml, hack/bundle-automation/chart-values/managed-serviceaccount/values.yaml, pkg/rendering/renderer.go, pkg/templates/charts/toggle/cluster-backup/values.yaml, pkg/templates/charts/toggle/cluster-lifecycle/values.yaml, pkg/templates/charts/toggle/cluster-permission/Chart.yaml, pkg/templates/charts/toggle/cluster-permission/values.yaml, pkg/templates/charts/toggle/console/values.yaml, pkg/templates/charts/toggle/grc/values.yaml, pkg/templates/charts/toggle/insights/values.yaml, pkg/templates/charts/toggle/multicloud-operators-subscription/values.yaml, pkg/templates/charts/toggle/multicluster-observability-operator/values.yaml, pkg/templates/charts/toggle/search-v2-operator/values.yaml, pkg/templates/charts/toggle/submariner-addon/values.yaml, pkg/templates/charts/toggle/volsync-controller/values.yaml
the hubSize value needs to be included in each of the values.yaml files.
There is one template that has not yet been updated, cluster-permission, as that values.yaml file is copied directly from the git repository https://github.com/stolostron/cluster-permission.git. This will need to be updated there before it can be updated here.
=> Hubsize chart

build/Dockerfile.rhtap, build/Dockerfile.test.rhtap
Adding new Dockerfile to for Konflux enablement.
https://issues.redhat.com/browse/ACM-10761
Added new Dockerfile for upstream sources.
=> [ACM-10761] Added RHTAP dockerfile

pkg/templates/charts/toggle/console/templates/console-search-configmap.yaml
Adds a ConfigMap that will house the suggested searches so users can customize searches and/or remove the default searches to increase search page performance. 
Additionally allows for other data fields to be included in the future for other pages that use search. 
https://issues.redhat.com/browse/ACM-11206
Only change is the addition of the new ConfigMap `console-search-config`
=> [ACM-11206] Add ConfigMap for cross product search config

pkg/templates/charts/toggle/console/templates/console-search-configmap.yaml
Use YAML block style indicator in `console-search-config` data to make string human readable.
https://issues.redhat.com/browse/ACM-11206
Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line:
/cc @dislbenn
=> Use yaml block style for console-search-config string

pkg/templates/charts/toggle/console/templates/console-search-configmap.yaml
https://issues.redhat.com/browse/ACM-10917
Add saved search for `kind:VirtualMachine` in `console-search-config` ConfigMap
=> [ACM-10917] Add saved search for kind:VirtualMachine

.github/workflows/regenerate-sha-commit.yml, Makefile.dev, hack/bundle-automation/generate-shell.py
Updated shell script to support new commit sha script.
https://issues.redhat.com/browse/ACM-11501
Updated `bundle-automation/generate-shell` script.
=> [ACM-11501] Updated shell script for automation

controllers/multiclusterhub_controller.go, pkg/templates/rbac_gen.go
Removed "MCH is invalid" log and added one to notify when the reconcile loop has completed successfully.
=> Removed confusing invalid MCH log message

controllers/managedcluster.go, controllers/multiclusterhub_controller_test.go
Removed invalid `connectionManager` and `prometheusIntegration` fields from `KlusterletAddOnConfig` resource.
```
❯ kubectl explain klusterletaddonconfig.spec
GROUP:      agent.open-cluster-management.io
KIND:       KlusterletAddonConfig
VERSION:    v1
FIELD: spec <Object>
DESCRIPTION:
KlusterletAddonConfigSpec defines the desired state of KlusterletAddonConfig
FIELDS:
applicationManager	<Object> -required-
ApplicationManagerConfig defines the configurations of ApplicationManager
addon agent.
certPolicyController	<Object> -required-
CertPolicyControllerConfig defines the configurations of
CertPolicyController addon agent.
clusterLabels	<map[string]string>
DEPRECATED in release 2.4 and will be removed in the future since not used
anymore.
clusterName	<string>
DEPRECATED in release 2.4 and …
```
=> Removed invalid fields from klusterletAddOnConfig resource

pkg/rendering/renderer.go, pkg/rendering/renderer_test.go, pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml, pkg/templates/charts/toggle/cluster-backup/values.yaml
- Fixed the missing double quotes issue for .Values.global.channel when parsed by helm (changed to .Values.global.minOADPChannel)
- Added a new entry in global variables called minOADPChannel to hardcode the minimum required OADP version. This field should not be updatable by user annotations.
- Removed the whole section of oadpOperator from the values.yaml since it was unused and ignored by MCH 
https://issues.redhat.com/browse/ACM-11855
- Added the double quotes so {{ printf `{{ $ch := "%s" }}` .Values.global.minOADPChannel }} results in  {{ $ch := "stable-1.3" }} when parsed by Helm
- Added a new entry in global variables called minOADPChannel to hardcode the minimum required OADP version. This field should not be updatable by user annotations.
- Removed the whole section of …
=> Fix the issues related to minimum OADP channel value

pkg/templates/crds/insights/wgpolicyk8s.io_policyreports.yaml
Updated to match https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/0fc2ddc5d3e396e9356e1769a1c0935cce1ba963/policy-report/crd/v1beta1/wgpolicyk8s.io_clusterpolicyreports.yaml
- https://issues.redhat.com/browse/ACM-7651
- https://github.com/stolostron/backlog/issues/27621
Updates the CRD.
/cc @mprahl @dislbenn
=> Update PolicyReport CRD to have v1beta1

.github/workflows/regenerate-bundles-2.11.yml, .github/workflows/regenerate-sha-commit-2.11.yml
=> Added GH Action config files for 2.11 automation

go.mod, go.sum
Updated `go.mod` dependencies to resolve CVE issue: https://github.com/advisories/GHSA-4v7x-pqxf-cx7m
https://issues.redhat.com/browse/ACM-12136
Updated `go.mod` to resolve CVE issue for `golang.org/x/net`.
=> [ACM-12136] Fixed golang.org/x/net cve

pkg/rendering/renderer.go, pkg/rendering/renderer_test.go, pkg/templates/charts/toggle/cluster-backup/values.yaml, pkg/templates/crds/cluster-backup/velero.io_backups.yaml, pkg/templates/crds/cluster-backup/velero.io_backupstoragelocations.yaml, pkg/templates/crds/cluster-backup/velero.io_deletebackuprequests.yaml, pkg/templates/crds/cluster-backup/velero.io_restores.yaml, pkg/templates/crds/cluster-backup/velero.io_schedules.yaml
Update ACM 2.10 to OADP 1.4
https://issues.redhat.com/browse/ACM-12197
Updated the OADP channel to 1.4 and updated the Velero CRDs accordingly.
=> [release-2.10] ACM-12197 - Update ACM 2.10 to OADP 1.4

.github/workflows/regenerate-bundles.yml
Updating `regenerate-bundles` make command to use the latest renamed command.
https://issues.redhat.com/browse/ACM-11975
Updated `regenerate-bundles` to use latest command.
=> [ACM-11975] Updated regenerate-bundles make command

Makefile.dev, hack/bundle-automation/generate-shell.py, pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-controller-manager.yaml, pkg/templates/charts/toggle/submariner-addon/templates/submariner-addon-clusterrole.yaml, pkg/templates/crds/multicloud-operators-subscription/apps.open-cluster-management.io_channels_crd_v1.yaml, pkg/templates/crds/multicloud-operators-subscription/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml, pkg/templates/crds/multicloud-operators-subscription/apps.open-cluster-management.io_multiclusterapplicationsetreports.yaml, pkg/templates/crds/multicloud-operators-subscription/apps.open-cluster-management.io_subscriptionreports_crd_v1alpha1.yaml, pkg/templates/crds/multicloud-operators-subscription/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, pkg/templates/crds/multicloud-operators-subscription/apps.open-cluster-management.io_subscriptionstatuses_crd_v1alpha1.yaml, pkg/templates/crds/submariner-addon/submarineraddon.open-cluster-management.io_submarinerconfigs.yaml
Updated the `make` command and automation script to fetch the latest script name for the bundle automation.
=> Updated bundle automation to fetch latest

.github/renovate.json
https://issues.redhat.com/browse/ACM-12674
=> [ACM-12674] Added renovate config for konflux

CONTRIBUTING.md, README.md, docs/available-components.md, docs/configuration.md
https://issues.redhat.com/browse/ACM-12412
=> [ACM-12412] Updated repository docs

hack/bundle-automation/config.yaml, hack/bundle-automation/copy-config.yaml
=> Update automation release branch ref to ACM 2.12

pkg/templates/charts/toggle/console/templates/console-plugin.yaml, test/unit-tests/crds/consoleplugin.yaml
consolePlugin chart template for acm updated from apiVersion v1alpha1 to v1
https://issues.redhat.com/browse/ACM-12354
consolePlugin chart template for acm was updated from apiVersion v1alpha1 to v1
=> [ACM-12354] Updated consolePlugin version from v1alpha1 to v1

pkg/templates/charts/toggle/grc/templates/grc-policy-addon-deployment.yaml, pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-deployment.yaml, pkg/templates/charts/toggle/grc/values.yaml
Updates:
- Remove kube-rbac-proxy sidecar from deployments
- Remove references to kube-rbac-proxy
- Remove proxy service YAML configuration
- Retain proxy RBAC permissions
ref: https://issues.redhat.com/browse/ACM-8346
=> Remove kube-rbac-proxy YAML configurations

hack/bundle-automation/config.yaml
Updated `submariner-addon` component to ACM 2.12 branch.
Updated `submariner-addon` branch from `release-2.11` to `release-2.12`.
=> Updated bundle-automation components to release-2.12

pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-deployment.yaml, pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-metrics-service.yaml, pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-metrics-servicemonitor.yaml
ref: https://issues.redhat.com/browse/ACM-8346
=> Move ports and volumeMounts from deprecated kube-rbac-proxy sidecar to controller container

config/crd/internal/internal-hub-component.yaml
Added InternalHubComponent CRD. Operator does not interact with it yet.
=> Internalhubcomponent

.github/workflows/update-pregenerated-charts.yml, OWNERS
=> Updated OWNERS file

hack/bundle-automation/config.yaml
Updated `hack/bundle-automation/config.yaml` to use latest `release-2.12` branch for `siteconfig` component. 
https://issues.redhat.com/browse/ACM-12523
Updated `siteconfig`branch from `main` to `release-2.12`.
=> [ACM-12523] Updated siteconfig branch ref to release-2.12

api/v1/multiclusterhub_methods.go, api/v1/multiclusterhub_webhook.go, api/v1/multiclusterhub_webhook_test.go, controllers/multiclusterhub_controller.go
https://issues.redhat.com/browse/ACM-13066
=> [release-2.10][ACM-13066] Updated webhook validation logic

api/v1/multiclusterhub_methods.go, api/v1/multiclusterhub_webhook.go, api/v1/multiclusterhub_webhook_test.go, controllers/multiclusterhub_controller.go
https://issues.redhat.com/browse/ACM-13066
=> [release-2.9][ACM-13066] Updated webhook validation logic

api/v1/multiclusterhub_webhook.go, api/v1/multiclusterhub_webhook_test.go
=> [release-2.12] Readded invalid component logic in webhook

api/v1/multiclusterhub_webhook.go, api/v1/multiclusterhub_webhook_test.go
=> [release-2.11] Readded invalid component logic in webhook

config/rbac/role.yaml, pkg/templates/charts/toggle/grc/templates/grc-clusterrole.yaml, pkg/templates/rbac_gen.go
Relates:
https://issues.redhat.com/browse/ACM-12790
=> GRC: Add the missing token creation privilege

api/v1/multiclusterhub_methods.go, api/v1/multiclusterhub_methods_test.go, controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go
Updated `siteconfig-preview` to `siteconfig` to represent GA'd status.
https://issues.redhat.com/browse/ACM-14205
Updated `siteconfig` to reflect GA status.
Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @dislbenn  @cameronmwall `
=> [ACM-14205] Added siteconfig, deprecated -preview

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml
Add human readable messages for the policy templates compliance status
https://issues.redhat.com/browse/ACM-14346
https://issues.redhat.com/browse/ACM-12110
Add human readable messages for the policy templates compliance status
Updated backup policy to explain each template status
=> add custom msgs for policy templates (ACM-14346, ACM-12110)

pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml
Followup to:
- #1722 
Address CI check: https://redhat-internal.slack.com/archives/C02UXRV7QP8/p1727071650030309
=> Align line breaks from Policy CRD

pkg/multiclusterengine/multiclusterengine.go
Jira Bug: ACM-14407
Fix the Stolostron-Engine channel for the ACM Community operator
Jira Bug: ACM-14407
Change the channel from community-0.4 to communit-0.5
Testing to see if it builds successfully.
=> Update the Stolostron-engine channel to community-0.5

.github/dependabot.yml, .github/workflows/rbac-gen.yaml, .github/workflows/regenerate-bundles.yml, config/rbac/role.yaml, controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go, pkg/templates/charts/toggle/cluster-permission/values.yaml, pkg/templates/rbac_gen.go, test/unit-tests/resources.go
The ingress value is currently being overridden even when it's discovered successfully.
Slack thread: https://redhat-internal.slack.com/archives/CUEMEHRA9/p1727470385708379
Removes the `r.CacheSpec.IngressDomain` check so that the Ingress is properly checked and the env set accordingly. 
-
I wondered whether the original goal was to _not_ re-fetch the ingress and have a conditional at the top, but since (I think?) the client caches the ingress, the re-fetch ought to be fairly cheap in case for whatever reason the ingress value changes.
=> Fix ingress logic

pkg/templates/crds/grc/policy.open-cluster-management.io_policyautomations.yaml
Sync changes from:
- https://github.com/stolostron/governance-policy-propagator/pull/860
=> Sync PolicyAutomation CRD

controllers/common.go
=> check CRD exists before trying to delete

Makefile.dev, hack/bundle-automation/generate-shell.py
=> Updated shell script for automation

pkg/templates/charts/toggle/insights/templates/insights-client-deployment.yaml
We are updating the insights-client service to use the v2 version of `https://console.redhat.com/api/insights-results-aggregator` API.
[ACM-14651](https://issues.redhat.com/browse/ACM-14651)
=> Update insights-results-aggregator API to v2

.github/workflows/regenerate-bundles-2.12.yml, .github/workflows/regenerate-sha-commit-2.12.yml
As we transition to ACM 2.13, this PR will add the Github actions files for ACM 2.12 to prepare for GA.
https://issues.redhat.com/browse/ACM-14818
Created ACM 2.12 Github action automation files.
=> [ACM-14818] Added GH Action config files for 2.12 automation

.tekton/multiclusterhub-operator-acm-212-pull-request.yaml, .tekton/multiclusterhub-operator-acm-212-push.yaml
Updating `.tekton` files to use the `release-2.12` branch, instead of the `main` branch.
=> [2.12] Updated tekton files branch ref

pkg/multiclusterengine/multiclusterengine.go, pkg/multiclusterengine/multiclusterengine_test.go, pkg/version/version.go
Updating MCE version reference from `2.7` to `2.8`.
Updated required `stable` channel for MCE in MCH operator.
=> Updated MCE version ref from 2.7 => 2.8

.github/workflows/regenerate-bundles.yml, .github/workflows/regenerate-sha-commit.yml, .github/workflows/update-pregenerated-charts.yml
=> Updated github actions jobs to run in parallel

hack/bundle-automation/config.yaml, hack/bundle-automation/copy-config.yaml
Updated the `config.yaml` branch references to `release-2.13` or `main` (temporary).
https://issues.redhat.com/browse/ACM-14816
Updated release branch ref for automation to `release-2.13`.
=> [ACM-14816] Update automation release branch ref to ACM 2.13

hack/bundle-automation/copy-config.yaml
=> Fixed branch ref in copy-config file

hack/bundle-automation/copy-config.yaml
=> [release-2.12] Fixed branch ref in copy-config file

pkg/templates/charts/toggle/console/templates/console-clusterrole.yaml, pkg/templates/rbac_gen.go
Gives the console cluster role list & watch permissions for search-operator.
=> console role list&watch search-operator permission

.tekton/multiclusterhub-operator-unit-test.yaml
Adding pipleine config to execute `unit-test` job in `konflux`. 
https://issues.redhat.com/browse/ACM-14839
Added `.tekton` file for unit testing in `konflux`.
=> [ACM-14839] Added unit-test job for Konflux

pkg/templates/charts/toggle/cluster-lifecycle/templates/klusterlet-addon-deployment.yaml
Refer to https://issues.redhat.com/browse/ACM-16213, remove limits for current hub controllers that have them
https://issues.redhat.com/browse/ACM-16203 
=> remove limit for server foundation components

controllers/multiclusterhub_controller.go
=> Resourcelogs

sonar-project.properties
To provide a more accurate assessment of our code quality, we will exclude YAML files from the analysis in this repository. These files currently include manifests from other squads, which are skewing the quality score for the actual operator. We plan to reintroduce YAML scans at a later stage.
https://issues.redhat.com/browse/ACM-15880
Updated the exclusion list to include YAML files.
=> [ACM-15880] Exclude YAML files from sonar scans

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup-policyset.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-config.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-placement-binding.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-placement.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore-config.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore-policyset.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-schedule-cron.yaml, pkg/templates/rbac.go
Package a new set of policies with the ACM backup chart. The policies will be used to backup or restore virtualmachines.kubevirt.io resources from hub or managed clusters.
Created a set of Policies and config maps to configure the policies.
Policies
- acm-dr-virt-install.yaml
- acm-dr-virt-backup.yaml
- acm-dr-virt-restore.yaml
Policy Sets
- acm-dr-virt-backup-policyset.yaml
- acm-dr-virt-restore-policyset.yaml
- acm-dr-virt-placement.yaml
Placement Binding
- acm-dr-virt-placement-binding.yaml
ConfigMaps
- acm-dr-virt-config.yaml
- acm-dr-virt-restore-config.yaml
- acm-dr-virt-schedule-cron.yaml
Tag the appropriate reviewers who should review this pull request. …
=> package VM backup and restore policies

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml
Add support to install oadp offline 
Updated install policy to allow passing a config for offline oadp install
=> oadp settings for offline scenarios

api/v1/multiclusterhub_methods.go
As we are onboarding the CAPI/CAPA components in this release, the list of MCE components referenced by MCH needs to be updated.
Updated MCE components list.
=> Updated MCE component list to contain new refs

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml, pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml
Validate configmap settings and show policy violations if files don't exist
https://issues.redhat.com/browse/ACM-16967
Create a new policy template for install, backup and restore policies to check that required config files were created by the user on the hub. Show violations otherwise
=> validate configmap settings

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml
Update cron job validation prop
Updates backup policy cron job validation property and use just the name of the vm with an invalid cron job, to avoid errors when the strings is longer than the allowed 64 char
=> update cron validation prop

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml
Add compliant custom message to config validation templates.
Updates the 3 policies and added custom message for the template that validates the configuration. It was unclear what the template was validating when compliant.
=> add compliant custom message

config/rbac/role.yaml, pkg/templates/charts/toggle/grc/templates/grc-policy-addon-clusterrole.yaml, pkg/templates/rbac_gen.go
Refs:
- https://issues.redhat.com/browse/ACM-14707
Add InternalHubComponent rbac to the policy-addon.
https://issues.redhat.com/browse/ACM-14707
Add InternalHubComponent rbac to the policy-addon.
=> Add InternalHubComponent rbac to the policy-addon

hack/bundle-automation/charts-config.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-db-deployment.yaml, pkg/templates/charts/toggle/flight-control/values.yaml, pkg/utils/utils.go
=> chart update

.tekton/multiclusterhub-operator-acm-213-pull-request.yaml, .tekton/multiclusterhub-operator-acm-213-push.yaml, .tekton/multiclusterhub-operator-pull-request.yaml, .tekton/multiclusterhub-operator-push.yaml, .tekton/multiclusterhub-operator-unit-test.yaml, build/Dockerfile.rhtap
Updated `.tekton` files to support `hermetic` image building.
https://issues.redhat.com/browse/ACM-17542
=> [ACM-17542] Added hermetic flag to konflux configs

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml, pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml
Moved configMap creation to install policy, removed from the backup and restore policies
Check user errors such as invalid cron or restore config map names passed through the main config
Moved configMap creation to install policy, removed from the backup and restore policies
=> refactor policy validation

api/v1/multiclusterhub_methods.go, controllers/multiclusterhub_controller.go, controllers/multiclusterhub_controller_test.go
=> Adding getcrd method to make sure we check for existing crds when creating mch or mce

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml
Validate the OADP CSV status is Succeeded
Updated install policy to validated that the OADP CSV status is Succeeded
- [] I have added/updated relevant unit tests (if applicable).
=> validate oadp csv status

controllers/common.go, controllers/multiclusterhub_controller.go
=> cleanup edge manager

hack/bundle-automation/chart-templates/templates/mutatingwebhookconfiguration.yaml, hack/bundle-automation/chart-templates/templates/validatingwebhookconfiguration.yaml, hack/bundle-automation/config.yaml
Added template for `webhookdefinitions` support for components that require webhook configurations for ACM/MCE.
https://issues.redhat.com/browse/ACM-17894
Added `validatingwebhookconfiguration` and `mutatingwebhookconfiguration` templates to `hack/bundle-automation/chart-templates`.
=> [ACM-17894] Added webhookdefinitions template for bundle-automation

controllers/multiclusterhub_controller.go
Currently, when some resource fails to deploy in ACM, we do not return the actual error from the client. Instead, we generate and return a custom error. This PR will update the error logging to capture the actual failure from the client.
Updated `deployResources` func to better capture error log.
=> Updated deployResources func log to capture client error

docs/available-components.md
=> Update list of deployed components

hack/bundle-automation/chart-requirements.txt
Currently, when we are attempting to run our `regenerate-charts` automation, we are missing a few package dependencies in our charts requirements file:
```py
pip3 install -r hack/bundle-automation/chart-requirements.txt
Collecting pyyaml (from -r hack/bundle-automation/chart-requirements.txt (line 1))
Downloading PyYAML-6.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting gitpython (from -r hack/bundle-automation/chart-requirements.txt (line 2))
Downloading GitPython-3.1.44-py3-none-any.whl.metadata (13 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython->-r hack/bundle-automation/chart-requirements.txt (line 2))
Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython->-r …
```
=> Updated chart requirements for automation

hack/bundle-automation/chart-values/flight-control/values.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-secrets-job.yaml
=> flight control automation bug

hack/bundle-automation/config.yaml, pkg/templates/charts/toggle/siteconfig-operator/templates/clusterinstances.siteconfig.open-cluster-management.io-validatingwebhookconfiguration.yaml, pkg/templates/charts/toggle/siteconfig-operator/templates/siteconfig-controller-manager.yaml, pkg/templates/charts/toggle/siteconfig-operator/templates/webhook-clusterinstances-siteconfig-open-cluster-management-io_v1_service.yaml
https://issues.redhat.com/browse/ACM-18309
=> [ACM-18309] site config web hook

.github/workflows/regenerate-bundles.yml, .github/workflows/regenerate-charts.yml, .github/workflows/regenerate-sha-commit.yml, .github/workflows/update-pregenerated-charts.yml
Modified `.github` configuration files to enable automation support for the `release-2.13` branch.
https://issues.redhat.com/browse/ACM-17969
Added `release-2.13` to `.github` config files.
=> [ACM-17969] Updated GH actions config files to support 2.13 automation

README.md
=> [2.14] Triggering image rebuild

pkg/templates/charts/toggle/console/templates/console-plugin.yaml, pkg/templates/charts/toggle/console/values.yaml
The `contentSecurityPolicy` for `ConsolePlugin` is behind a feature gate in OCP v4.18 but will be enabled by default in v4.19.
Followup to:
- #2079 
- https://issues.redhat.com/browse/ACM-17765
Conditionally renders `contentSecurityPolicy` for `ConsolePlugin` per description.
Current state of MCH:
```yaml
- lastTransitionTime: "2025-03-20T19:39:40Z"
lastUpdateTime: "2025-03-20T19:39:40Z"
message: 'failed to update resource Kind: acm Name: ConsolePlugin: failed to
create typed patch object (/acm; console.openshift.io/v1, Kind=ConsolePlugin):
.spec.contentSecurityPolicy: field not declared in schema'
reason: FailedApplyingComponent
status: "True"
type: 'ComponentFailure: acm (Kind:ConsolePlugin)'
```
MCH logs show that it can create it but not patch it:
```
2025-03-20T19:38:06.643Z	INFO …
```
=> Conditionally render console `contentSecurityPolicy`

pkg/rendering/renderer.go, pkg/utils/annotations.go
=> edge manager annotation storage class

pkg/rendering/renderer.go, pkg/rendering/renderer_test.go, pkg/templates/charts/toggle/cluster-backup/values.yaml
* startingCSV can now be set via annotation
* updated unit tests
---------
=> [2.13] startingCSV can now be set via annotation

pkg/rendering/renderer.go, pkg/rendering/renderer_test.go, pkg/templates/charts/toggle/cluster-backup/values.yaml
* startingCSV can now be set via annotation
* updated unit tests
=> [2.12] startingCSV can now be set via annotation

pkg/rendering/renderer.go, pkg/rendering/renderer_test.go, pkg/templates/charts/toggle/cluster-backup/values.yaml
* startingCSV can now be set via annotation
* updated unit tests
=> [2.11] startingCSV can now be set via annotation

pkg/rendering/renderer.go, pkg/rendering/renderer_test.go, pkg/templates/charts/toggle/cluster-backup/values.yaml
* startingCSV can now be set via annotation
* updated unit tests
=> [2.10] startingCSV can now be set via annotation

go.mod
Fix the following CVE by updating go:
- `CVE-2025-22868`
=> Bump go version to v1.23.6 to resolve CVE-2025-22866

pkg/templates/charts/toggle/cluster-backup/templates/odap-operator-pre-install-hook.yaml
use startingCSV on oadp chart installation
https://issues.redhat.com/browse/ACM-19859
allow setting the startingCSV property on the installer.open-cluster-management.io/oadp-subscription-spec annotation
=> https://issues.redhat.com/browse/ACM-19859 - use startingCSV on oadp chart installation

Makefile.dev, hack/bundle-automation/chart-requirements.txt, hack/bundle-automation/generate-shell.py, hack/bundle-automation/requirements.txt
=> Updated generate-shell script (v2)

hack/bundle-automation/charts-config.yaml, hack/bundle-automation/config.yaml
=> Added global version support for automation config

Makefile.dev, hack/bundle-automation/chart-requirements.txt, hack/bundle-automation/generate-shell.py
=> Updated pipeline branch config for 2.12

Makefile.dev
=> Updated pipeline branch config for 2.14

pkg/templates/charts/toggle/console/templates/acm-cli-consoleclidownload.yaml
Removes "Dev Preview" from dryrun CLI description.
- https://issues.redhat.com/browse/ACM-20097
Update `ConsoleCLIDownload` manifest for `acm-cli`.
-
-
=> Remove "dev preview" from dryrun CLI

controllers/managedcluster.go
In 2.11 a regression was introduced which prevents changes to the kluste let addon config as they are overridden on reconcile. This change reverses the code change that was made as discussed here
[ACM-18300](https://issues.redhat.com/browse/ACM-18300?filter=-1)
=> klusterletaddonconfig proxy regression reversal

.tekton/multiclusterhub-operator-acm-214-push.yaml, .tekton/multiclusterhub-operator-push.yaml
Configured additional build platforms on Konflux to support multi-architecture builds:
```yaml
- name: build-platforms
value:
- linux/x86_64
- linux/ppc64le
- linux/s390x
- linux/arm64
```
https://issues.redhat.com/browse/ACM-20954
Updated `push` files to support `multi-arch` enablement.
=> [ACM-20954] Configured multi-arch support for konflux build

Makefile.dev, hack/bundle-automation/generate-shell.py
=> [release-2.10] Updated generate-shell script (v2)

hack/bundle-automation/generate-shell.py
Updated the shell script to utilize the `./scripts` directory in the `installer-dev-tools` repository for improved script handling.
https://issues.redhat.com/browse/ACM-18687
Updated shell script path references.
=> [ACM-18687] Updated shell script path references for automation tools

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
=> Added required annotations to ACM CSV

controllers/status.go, pkg/templates/crds/multicluster-observability-operator/observability.open-cluster-management.io_multiclusterobservabilities.yaml
MCH should not report "Running" if CRDs fail to deploy. A HubCondition check was added during the phase aggregation to see if the Progressing status reason was "DeployFailedReason"
=> ACM-19114 MCH should not report "Running" if CRDs fail to deploy

pkg/templates/charts/toggle/console/templates/acm-cli-consoleclidownload.yaml
ref: https://issues.redhat.com/browse/ACM-21053
Adds download links for added CLI binary architectures.
https://issues.redhat.com/browse/ACM-21053
Adds the binary download links
=> Add ACM CLI download links for IBM Z/Power

.tekton/multiclusterhub-operator-acm-213-pull-request.yaml, .tekton/multiclusterhub-operator-acm-213-push.yaml
=> [release-2.13] Updated tekton files to resolve EC failures

pkg/templates/charts/toggle/fine-grained-rbac/templates/policy-virt-clusterroles-policy.yaml
This fixes some issues identified by QE in the base implementation. Refs:
- https://issues.redhat.com/browse/ACM-21408
=> Limit labels to the ones requested by virt team

.tekton/multiclusterhub-operator-acm-212-push.yaml
Adding support for additional architectures
- linux/x86_64
- linux/ppc64le
- linux/s390x
- linux/arm64
https://issues.redhat.com/browse/ACM-22410
=> [ACM-22410] [release-2.12] Adding support for additional architectures

.tekton/multiclusterhub-operator-unit-test.yaml, CONTRIBUTING.md, Dockerfile, build/Dockerfile.prow, build/Dockerfile.rhtap, build/Dockerfile.test.prow, controllers/status_test.go, go.mod, pkg/overrides/overrides.go, pkg/rendering/renderer_test.go
=> Updated to go 1.24.4

README.md
Need new pipeline build so pushing changes here
=> Request rebuild because we need a new pipeline for the 29 release

README.md
Reverts stolostron/multiclusterhub-operator#2594
=> Revert "Request rebuild because we need a new pipeline for the 29 release"

bundle.Dockerfile, bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml, bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml, bundle/metadata/annotations.yaml, go.sum
Bundle was not built, and CRD is out of date
=> Built bundle for ACM

hack/bundle-automation/charts-config.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-alert-exporter-deployment.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-alertmanager-config-configmap.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-alertmanager-proxy-config-configmap.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-alertmanager-proxy-deployment.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-api-deployment.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-cli-artifacts-deployment.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-db-deployment.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-db-migration-1-job.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-periodic-deployment.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-ui-deployment.yaml, pkg/templates/charts/toggle/flight-control/templates/flightctl-worker-deployment.yaml, pkg/templates/charts/toggle/mtv-integrations/values.yaml
=> edge management image update security context

controllers/common.go
https://issues.redhat.com/browse/ACM-24979
=> [ACM-24979] Annotation is no longer missing
