stolostron/multiclusterhub-operator

templates/multiclusterhub/base/apiserver/apiservice-clusterview_v1.yaml
templates/multiclusterhub/base/apiserver/apiservice-clusterview_v1alpha1.yaml

story: https://github.com/open-cluster-management/backlog/issues/9691
The aggregated api group `clusterview.open-cluster-management.io` has the same resources `managedCluster` and 
`managedClusterSet` with the group `cluster.open-cluster-management.io` . 
Lower the priority of group `clusterview.open-cluster-management.io` to make sure that the resources in group `cluster.open-cluster-management.io` could be preferred by client, like  `oc get managedcluster/managedclusterset`.

lower the aggregated api group priority

---

cicd-scripts/gather-crds.sh

The gather-crdsd script was unintentionally picking up non-CRD YAML files.  This change constrains it to look only within the `crds` directory tree.

Have gather script look only in crds directory

---

pkg/controller/multiclusterhub/common.go
pkg/controller/multiclusterhub/common_test.go

Only check subscription operator version if installed as a composite bundle (where olm.owner is advanced-cluster-management instead of multicluster-hub)

Update AppSub Version Check

---

Makefile

when it was removed: https://github.com/open-cluster-management/multicluster-observability-operator/pull/429
where it is now: https://github.com/open-cluster-management/multicluster-observability-operator/blob/main/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml

new observability crd addr

---

templates/multiclusterhub/base/webhook/webhook-mutating-config.yaml

Signed-off-by: Joshua Packer <jpacker@redhat.com>
* Add the owner-identifier so the UI can display who created the object for:
* clusterdeployment
* clusterPool
* clusterClaim

Add support for hive objects to have a create owner-identifier

---

pkg/rendering/crd_renderer.go

Issue: https://github.com/open-cluster-management/backlog/issues/12080
Check for cert-manager CRDs not needed since they were removed in https://github.com/open-cluster-management/hub-crds/pull/49 and won't be installed again

Remove check for cert-mgr CRDs

---

deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml
deploy/role.yaml
templates/multiclusterhub/base/rbac/clusterrole-admin-aggregate.yaml
templates/multiclusterhub/base/rbac/clusterrole-clustermanageradmin-aggregate.yaml
templates/multiclusterhub/base/rbac/clusterrole-edit-aggregate.yaml
templates/multiclusterhub/base/rbac/clusterrole-view-aggregate.yaml

Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>
Additions assume clustercurator rbac is equivalent to managedcluster rbac. 
clusterrole-foundation.yaml is an exception, as it isn't clear to me how the curator rbac should be defined in that context. Thus no changes to that yaml have been made in this PR (am looking for some guidance on how to approach that). 
If this is assumption about the curator's rbac is correct, I am hoping to get this PR approved. If not, the hope is to open up the discussion about how we should define it.

cluster curator added to rbac aggregate

---

pkg/controller/multiclusterhub/uninstall.go

Issue: https://github.com/open-cluster-management/backlog/issues/10539
If the CRDs are removed it would also impact other products that depend on RHACM such as MCM.

Keep cert-manager CRDs on upgrade

---

pkg/channel/channel.go
pkg/channel/channel_test.go
pkg/controller/multiclusterhub/common.go

Issue: https://github.com/open-cluster-management/backlog/issues/10504
Verified with clean install and on upgrade (with pre-existing non-annotated channel present)

Add annotation to HelmRepo channel

---

pkg/foundation/foundation.go
pkg/foundation/foundation_test.go
pkg/foundation/proxy_server.go
pkg/foundation/webhook.go
pkg/helmrepo/helmrepo.go
pkg/helmrepo/helmrepo_test.go
pkg/utils/utils.go

Issue: https://github.com/open-cluster-management/backlog/issues/15356
The ocm-antiaffinity-selector label added in 2.2 is not properly applied
to deployments or their pod templates. In 2.3 the services were updated to
set this label in their selector while it is still missing from the pods. This
change will remove the antiaffinity label from the service selector and add it
to the pod template if it is missing.

Validate deployment labels are updated

---

controllers/common.go
pkg/channel/channel.go
pkg/channel/channel_test.go

While the mch is installing or upgrading the appsub reconcile rate will
be set to high. Once the desired version has been reached it will be
set to low.

Update channel annotation dynamically

---

pkg/channel/channel.go
pkg/channel/channel_test.go
pkg/controller/multiclusterhub/common.go

Issue: https://github.com/open-cluster-management/backlog/issues/15991
While the mch is installing or upgrading the appsub reconcile rate will
be set to high. Once the desired version has been reached it will be
set to low.

Update channel annotation dynamically (2.3)

---

controllers/common.go
pkg/multiclusterengine/multiclusterengine.go
test/function_tests/multiclusterhub_install_test/multiclusterhub_test.go

Issue: https://github.com/stolostron/backlog/issues/18902
If the MCH sets an imagePullSecret it is copied to the MCE namespace and set in the MCE spec. If the MCH imagePullSecret is then removed, it is also removed from MCE spec and deleted from the MCE namespace.

Clone imagepullsecret from MCH namspace to MCE

---

bin/image-manifests/2.5.0.json
controllers/common.go
controllers/multiclusterhub_controller.go

Issue: https://github.com/stolostron/backlog/issues/21176
Add watch to clusterversion resource and pass one of two oauth images
to overrides depending on OCP version.

Watch clusterversion and override oauth image

---

api/v1/multiclusterhub_types.go
bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
config/manifests/bases/multiclusterhub-operator.clusterserviceversion.yaml

Issue: https://github.com/stolostron/backlog/issues/21839

removed deprecated mch specs from MultiClusterHub overview in UI

---

controllers/common.go

currently the pull secret replicated to the MCE namespace is of type `Opaque` which is the incorrect type for a pull secret is `kubernetes.io/dockerconfigjson`
corev1 documentation reference https://pkg.go.dev/k8s.io/kubernetes/pkg/apis/core
```
// SecretTypeDockerConfigJSON contains a dockercfg file that follows the same format rules as ~/.docker/config.json
//
// Required fields:
// - Secret.Data[".dockerconfigjson"] - a serialized ~/.docker/config.json file
[SecretType](https://pkg.go.dev/k8s.io/kubernetes/pkg/apis/core#SecretType)DockerConfigJSON SecretType = "kubernetes.io/dockerconfigjson"
```
NOTE: this field is immutable therefore if upgrade is required additional code maybe need to be added. It maybe easier to fix it now where previous ACM does not depend on MCE than in a later …

add correct type for mcePullSecret

---

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
config/manager/manager.yaml

fix issue: https://github.com/stolostron/backlog/issues/21711
mimic change https://github.com/stolostron/backplane-operator/pull/224

increase the mem limit to fix the mch-operator oom in 2k clusters

---

.gitignore
Makefile
build/Dockerfile.test.prow
pkg/subscription/cluster_backup.go

Issue: https://github.com/stolostron/backlog/issues/24780
Calling setCustomCA on a subscription without overrides causes a panic
because the overrides field is nil.

[release-2.5] Remove setCustomCA call to avoid type assertion on nil

---

Makefile
api/v1/multiclusterhub_methods.go
controllers/common.go
controllers/multiclusterhub_controller.go

The upgrade logic was moved further down in the `controllers/multiclusterhub_controller.go` file, but the diff below shows the code it was moved past as being moved instead of the upgrade logic being moved.

fix upgrade logic for fresh install

---

controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
controllers/uninstall.go
pkg/rendering/renderer.go
pkg/rendering/renderer_test.go
pkg/templates/charts/toggle/cluster-lifecycle/Chart.yaml
pkg/templates/charts/toggle/cluster-lifecycle/templates/clustermanagementaddon-clusterrole.yaml
pkg/templates/charts/toggle/cluster-lifecycle/templates/clustermanagementaddon-clusterrolebinding.yaml
pkg/templates/charts/toggle/cluster-lifecycle/templates/klusterlet-addon-deployment.yaml
pkg/templates/charts/toggle/cluster-lifecycle/templates/klusterlet-addon-role.yaml
pkg/templates/charts/toggle/cluster-lifecycle/templates/klusterlet-addon-role_binding.yaml
pkg/templates/charts/toggle/cluster-lifecycle/templates/klusterlet-addon-service_account.yaml
pkg/templates/charts/toggle/cluster-lifecycle/values.yaml
pkg/templates/crds/cluster-lifecycle/agent.open-cluster-management.io_klusterletaddonconfigs_crd.yaml
pkg/utils/utils.go
pkg/utils/utils_test.go

Issue: https://github.com/stolostron/backlog/issues/25587
Moves source-of-truth for MCH cluster lifecycle templates from https://github.com/stolostron/multiclusterhub-repo/tree/main/multiclusterhub/charts/cluster-lifecycle/templates and CRDs from https://github.com/stolostron/hub-crds/tree/main/crds/cluster-lifecycle-chart to this repo.

Render cluster-lifecycle chart directly

---

pkg/templates/crds/grc/policy.open-cluster-management.io_policyautomations.yaml

Signed-off-by: Will Kutler <wkutler@redhat.com>
For https://github.com/stolostron/backlog/issues/20158 we added a new "jobttl" field to the GRC policy automation CRD. This PR updates the copy of the CRD in multiclusterhub-operator.

update grc policy automation crd

---

pkg/templates/crds/grc/policy.open-cluster-management.io_placementbindings.yaml

In preparation for CRD sync checks, this brings in changes to the CRD that hadn't previously been synced.

Sync GRC PlacementBinding CRD

---

pkg/templates/charts/toggle/grc/templates/grc-clusterrole.yaml

the 'create' permission on TokenReview and SubjectAccessReview is required by kube-rbac-proxy container in the propagator deployment for controlling access to metrics endpoint
related to:
https://github.com/stolostron/backlog/issues/26873
https://github.com/stolostron/backlog/issues/26574
Signed-off-by: Chaitanya Kandagatla <ckandaga@redhat.com>

Add permissions required by the kube-rbac-proxy

---

pkg/templates/charts/toggle/grc/templates/grc-clusterrole.yaml

Removing permissions for  configmaps as
Leader Election, for which  ConfigMaps was needed, has since been removed
related to : stolostron/backlog#26574
Signed-off-by: Chaitanya Kandagatla <ckandaga@redhat.com>

Reduce permissions on grc clusterrole,

---

pkg/templates/charts/toggle/grc/templates/grc-policy-addon-clusterrole.yaml

Relates:
https://issues.redhat.com/browse/ACM-2176
https://github.com/stolostron/backlog/issues/26713
Signed-off-by: mprahl <mprahl@users.noreply.github.com>

Add GRC permissions for AddOnDeploymentConfig placement configurations

---

pkg/templates/charts/toggle/grc/templates/grc-policy-addon-clusterrole.yaml

When upgrading ACM 2.6 to 2.7 there was a permissions problem that kept the upgrade from working.  These permissions were needed.
Refs:
- https://issues.redhat.com/browse/ACM-2355
Signed-off-by: Gus Parvin <gparvin@redhat.com>

ACM upgrade to 2.7 failed in grc addon with permissions

---

pkg/templates/charts/toggle/console/templates/console-deployment.yaml

https://github.com/stolostron/backlog/issues/22342
Use default failureThreshold (3)
Allow 5 seconds for timeout for hubs with large workloads

Fix console-chart scale issues

---

controllers/managedcluster.go
controllers/managedcluster_test.go
controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go

https://issues.redhat.com/browse/ACM-2231
When re-enabling the local cluster, there will be several errors reported while waiting for the `local-cluster` namespace to be recreated.

jira acm-2231: fix missing managed cluster addons

---

pkg/templates/charts/toggle/console/templates/console-clusterrole.yaml

Signed-off-by: Kevin Cormier <kcormier@redhat.com>

Fix typo in API name: storageclass -> storageclasses

---

pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_restores.yaml
pkg/templates/crds/cluster-backup/velero.io_restores.yaml

Signed-off-by: Valentina Birsan <vbirsan@redhat.com>
Changes:
- update velero CRD with version 1.9.4, which is the version mapping to oadp 1.1.1
- update acm restore CRD to include 2 extra optional properties used by velero restore https://github.com/stolostron/backlog/issues/26919

update backup CRD

---

pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-application.yaml

Signed-off-by: Xiangjing Li <xiangli@redhat.com>
https://issues.redhat.com/browse/ACM-2336
The memory limit for the placementrule controller is increased to 1.5 for better support of 3k cluster scale test

increase placementrule memory limit to 1.5G

---

pkg/templates/charts/toggle/console/templates/console-deployment.yaml

Also removes obsolete env FRONTEND_URL and BACKEND_URL
https://github.com/stolostron/backlog/issues/22342
Adds environment variable switch to disable resource watching and the events API in the console backend. ACM plugin data fetching is shared with MCE in 2.7, so there is no reason for the ACM pods to consume memory and CPU watching resources for data that will never be queried.

console: Set new env to DISABLE_EVENTS for ACM

---

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/multiclusterhub_controller.go
controllers/uninstall.go

Adds a step during upgrade to delete the GRC appsub and helmrelease and prevent finalizer logic from taking place. This is to preserve all GRC ClusterManagementAddOns when upgrading from 2.6 to 2.7.

GRC upgrade procedure for 2.6->2.7

---

pkg/templates/multiclusterhub/base/multicluster-applications-rbac-aggregate-admin.yaml
pkg/templates/multiclusterhub/base/multicluster-applications-rbac-aggregate-edit.yaml
pkg/templates/multiclusterhub/base/multicluster-applications-rbac-aggregate-view.yaml

This mimics what OLM did when the app lifecycle CRDs were included in the ACM bundle.
Jira: https://issues.redhat.com/browse/ACM-3055 & https://issues.redhat.com/browse/ACM-3203

Add rbac aggregation for app lifecycle CRDs

---

pkg/templates/charts/toggle/grc/OWNERS
pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-deployment.yaml

- Adds a default container for the governance-policy-propagator as a convenience so that `oc logs` defaults to the propagator rather than the proxy
- Also adds an OWNERS file for the GRC chart

Default governance-policy-propagator container

---

controllers/common.go
go.mod
go.sum
pkg/multiclusterengine/multiclusterengine.go
pkg/multiclusterengine/multiclusterengine_test.go
pkg/version/version.go
test/function_tests/multiclusterhub_install_test/multiclusterhub_full_test.go
test/function_tests/multiclusterhub_update_test/multiclusterhub_test.go

Issue: https://issues.redhat.com/browse/ACM-3331
In addition to determining which catalogsource to use for MCE based on available channel, select the catalogsource with the latest available version within that channel.

Auto-select MCE catalogsource based on latest available version

---

pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-applications-clustermanagementaddon.yaml

Our bundle-update automation is not recognizing/picking up ClusterManagementAddon resources from the source bundle.  So the last bundle-update PR was incomplete and deleted this part out of the App Sub templates directly.  
I will work on updates to the generate-bundle script, but to unblock the AppSub folks I am just manually adding the part back.  The auto-generated bundle update PR will once again want to delete this part out, so we should just leave that PR pending (eventually delete it) until the fixes to generate-bundle are in.

Add back AppSub part that is not being picked up by bundle automation

---

api/v1/webhook_test.go
controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
main.go

Add a watch of mce in multiclusterhub-operator so if MCE gets changed, multiclusterhub-operator notices that it is not configured to match MCH's configuration, and changes it back
Changed the way SetupWithManager function works to return a controller that can be used to add a watch whenever mce is found, if so add a watch to it.

intial commit of adding a watch on mce

---

pkg/templates/charts/toggle/grc/templates/cert-policy-clustermanagementaddon.yaml
pkg/templates/charts/toggle/grc/templates/config-policy-clustermanagementaddon.yaml
pkg/templates/charts/toggle/grc/templates/governance-policy-framework-clustermanagementaddon.yaml
pkg/templates/charts/toggle/grc/templates/iam-policy-clustermanagementaddon.yaml

Previously we added permissions so that the policy-addon-controller could use these resources for configuring some details of addons on managed clusters, specifically to help configuration of nodeSelectors and tolerations. But in order to apply a configuration, both the CMAO and the MCAO would need to be updated to allow it. This change makes it so that only the MCAO needs to be updated, to specifically point to an addondeploymentconfig.
It does not result in any changes by default. It only makes it easier to configure in the future.
Refs:
- https://issues.redhat.com/browse/ACM-1706
- https://github.com/stolostron/multicloud-operators-foundation/pull/532/files#diff-8baaa1096e19937690454565dfd62a62a10ca325aff30a7f543748cf52ec75e1
- …

Support addondeploymentconfigs for grc addons

---

pkg/multiclusterengine/multiclusterengine.go
pkg/multiclusterengine/multiclusterengine_test.go

When the MCH image repository override annotation is set and then removed the annotation remained on MCE. This fix makes sure the override is unset.
Jira: https://issues.redhat.com/browse/ACM-5184

ACM-5184: Fix issue where MCE override annotation not removed

---

pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-integrations.yaml
pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-application.yaml
pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-channel.yaml
pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-hub-subscription.yaml
pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-standalone-subscription.yaml
pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-operators-subscription-report.yaml
pkg/templates/charts/toggle/search-v2-operator/templates/search-v2-operator-controller-manager.yaml

This PR is the result of a manual bundle-to-chart run on the release-2.8 branch after the changes made by PRs #1042 were merged into this branch.
This is *not* a cherry pick from a similar update done to the `main` branch since the `main` branch now already represents the `release-2.8` release.

Manual bundle-to-charts update for release-2.8

---

main.go
pkg/webhook/setup.go

This reverts commit e3928dabb23d155aa1d0148c8126fb48ccaa37c2.
Jira: https://issues.redhat.com/browse/ACM-5997

Revert "Update webhook server tls min version to 1.3 (#1029)"

---

pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-deployment.yaml
pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-webhook-service.yaml
pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-webhook-validate-config.yaml

governance-policy-propagator newly add the webhook for validating policy name. This webhook needs the service, certification and the ValidatingWebhookConfiguration accordingly.
ref: https://issues.redhat.com/browse/ACM-3558

[ACM-3558]add service and validateConfig for grc-policy-propagator 

---

controllers/multiclusterhub_controller.go

These changes will fix the incorrect path for the `clusterpermission` chart location.

Fixed clusterpermission chart location

---

controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
go.mod
go.sum
hack/prereqs/kustomization.yaml
hack/prereqs/oc.yaml
main.go
pkg/utils/operatorconditions.go
pkg/utils/operatorconditions_test.go

This is a  backport of  identical code from 2.8 which  should use operator conditions to prevent upgrading unless the MCH is available

[ACM-6959] backport operator conditions

---

api/v1/multiclusterhub_methods.go
api/v1/multiclusterhub_methods_test.go
controllers/common.go
controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
main.go
test/unit-tests/resources.go

Before the `submariner-addon` component can be cleaned up and removed, we need to ensure that the `ClusterManagementAddOn` is removed from the cluster. This will allow MCH to proceed with the component removal.
https://issues.redhat.com/browse/ACM-7574
Update the disable/uninstall process to ensure that the `ClusterManagementAddOn` CR is removed for the `submariner-addon` before removing the `submariner-addon` component.
/cc @ngraham20 @cameronmwall 
/hold

[ACM-7574] Remove submariner ClusterManagementAddOn as pre-req to cleanup

---

controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
controllers/uninstall.go
pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-metrics-prometheusrule.yaml
pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-metrics-servicemonitor.yaml

Move the GRC Prometheus configuration out of the openshift-monitoring ns.
It is a best practice to not add PrometheusRules and ServiceMonitors in the openshift-monitoring namespace. Instead a namespace can have the openshift.io/cluster-monitoring label set for the Prometheus operator to use this configuration.
This also handles deleting the old GRC Prometheus configuration in the openshift-monitoring namespace.
https://issues.redhat.com/browse/ACM-7633
The GRC PrometheusRule and ServiceMonitor are placed in the controller's namespace instead of the openshift-monitoring namespace. The existing objects in the openshift-monitoring namespace are deleted.
I haven't tried running this locally but the unit test is …

Move the GRC Prometheus configuration out of the openshift-monitoring ns

---

pkg/templates/charts/toggle/console/templates/console-prometheus-rules.yaml

Includes a PrometheusRule resource that exposes a metric: acm_console_page_count:sum. This metric sums all page visits across the ACM Console, and reduces the cardinality of the original metric so we can upload to Telemetry.
https://issues.redhat.com/browse/ACM-7492
The PR adds a PrometheusRule resource for the acm console. The PromRule resource will include one rule that sums page count visits across the console pods (running and previous).

Console PrometheusRule for page visit counts

---

api/v1/multiclusterhub_methods.go
api/v1/multiclusterhub_methods_test.go
controllers/multiclusterhub_controller.go
controllers/uninstall.go
pkg/utils/utils.go
test/unit-tests/resources.go

Updated MCH operator to create a `service` and `servicemonitor` to allow OCP to begin collecting `controller-runtime` metrics for the operator.
https://issues.redhat.com/browse/ACM-8547
Updated MCH operator to deploy metrics `service` and `servicemonitor` to collect `controller-runtime` metrics.
/cc @cameronmwall @ngraham20 
/hold

[ACM-8547] Added service and servicemonitor to collect MCH operator metrics

---

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml

Updating MCH operator to support 2 replicas.
https://issues.redhat.com/browse/ACM-8781
Updated CSV to include 2 replicas for MCH operator pods.
/cc @ngraham20 @cameronmwall

[ACM-8781] Updated multiclusterhub-operator replicas count to 2

---

api/v1/multiclusterhub_types.go
controllers/status.go
controllers/status_test.go

Updated MCH operator to show `Pending` status when the MCH CR has the `mch-pause` annotation set to `true`.
https://issues.redhat.com/browse/ACM-9005
Updated MCH CR to show a `Pending` status when the MCH operator is paused.

[ACM-9005] Updated multiclusterhub phase status to Paused when the operator is paused

---

pkg/multiclusterengine/multiclusterengine.go

Just as each version of ACM requires a specific version of MCE, so too does each version of the community Stolostron operator requires a corresponding version of Stolostron Engine.  For the ACM 2.10 release cycle, the product pairings are ACM 2.10 / MCE 2.5 and the community pairings are Stolostron 0.3 / Stolostron-Engine 0.3. 
The update to the required Stolostron-Engine channel was not made by PR #1244 but should have been.  ACtually, it looks like no update was made  for ACM 2.9 / Stolostron 0.2 either (oops!).
Update the constant identifying the required Stolostron-Engine update channel.

Update channel for stolostron-engine to 0.3

---

pkg/multiclusterengine/multiclusterengine.go
pkg/multiclusterengine/multiclusterengine_test.go

The ACM Hub operator has logic to automatically determine the catalog source to use when creating the OLM subscription to install MCE.  This logic looks through the `PackageManifest` resources for the MCE operator package (there will be one of these per `CatalogSource` that provides the package), and seeks to pick the `PackageManifest/CatalogSource` that includes the update channel we need for this ACM release.  
In normal cases, there is usually only one `PackageManifest`/`CatalogSource` (the built-into-OCP `redhat-operators`  `CatalogSource`) that provides the operator package, so there is no possibility of ambiguity.  But in special customer situations or in dev, there can be many, so there can be multiple ones that provide the needed update channel.  If there are multiple and one of …

Fix MCE catsrc ambiguity detection when more than 1 catsrc has latest version

---

controllers/hosted.go
controllers/multiclusterhub_controller.go
main.go
pkg/multiclusterengine/multiclusterengine.go
pkg/multiclusterengine/subscription.go
pkg/rendering/renderer.go

There was a lot of excess information in every log statement. This has been removed.
https://issues.redhat.com/browse/ACM-8349
Change the log function from `log.FromContext()` to `log.Log.WithName()`

remove context from logs

---

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-clusterrolebinding.yml
test/unit-tests/crds/managedclustersetbindings.yaml

Addition to https://github.com/stolostron/multiclusterhub-operator/pull/1289
The Placement resource needs a ManagedClusterSetBinding created in the same ns with the Placement
https://issues.redhat.com/browse/ACM-8892
Created a ManagedClusterSetBinding for the default clusterSet in the open-cluster-management-backup namespace, where the hub backup resources are installed 

create ManagedClusterSetBinding for the backup ns

---

api/v1/methods_test.go
api/v1/multiclusterhub_methods.go
api/v1/multiclusterhub_webhook.go
controllers/multiclusterhub_controller.go

Updating the validating webhook for MCH to validate and compare entries only against valid MCH components. This will prevent users from adding MCE component names to the MCH CR resource.
https://issues.redhat.com/browse/ACM-9642
Updated MCH validating webhook to validate and accept components, only if they are valid MCH components.

[ACM-9642] Updated validating webhook to only ensure MCH components

---

api/v1/multiclusterhub_methods.go
controllers/multiclusterhub_controller.go

Updating the MCH operator to `prune` any MCE component that is detected within the MCH CR.
https://issues.redhat.com/browse/ACM-9574
Updated the operator to prune MCE components from the MCH CR.

[ACM-9574] Ensuring that non-mch components are removed from spec.override

---

controllers/common.go
pkg/multiclusterengine/multiclusterengine.go
pkg/multiclusterengine/multiclusterengine_test.go

One thing I noticed, is that this code was the only reason that `NewMultiClusterEngine` accepts the custom namespace. Is it safe to remove this?

Removed assisted service namespace allocation for MCE

---

pkg/templates/charts/toggle/cluster-permission/templates/cluster-permission.yaml

enable readOnlyRootFilesystem on hub cluster permission pod
https://issues.redhat.com/browse/ACM-8463

enable readOnlyRootFilesystem on cluster permission pod

---

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml

Adding a new policy template to find the OADP subscription and check if its channel version is what we have in Values.yaml file. If another version of OADP is manually installed by users, the policy shows as non compliant.
Note: The purpose for the backticks is for the Helm to process the template and return the raw string inside (i.e. the Policy template). We don't want Helm to process the policy templates.
https://issues.redhat.com/browse/ACM-8490
Adding a new policy template to find the OADP subscription and check if its channel is what we have in Values.yaml file
Tag the appropriate reviewers who should review this pull …

Adding a policy template to verify OADP channel

---

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-auto-import.yaml
pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-policy-set.yaml
pkg/templates/charts/toggle/cluster-backup/templates/managed-hub-policy-set.yaml

A new policy is added to both _acm-hub-backup_ and _acm-managed-hub-backup_ policy sets. It includes two templates:
- _auto-import-account-secret_ **informs** if in managed cluster namespaces other than local-cluster, there is a ManagedServiceAccount named auto-import-account, but there is not a secret named auto-import-account
- _auto-import-backup-label_ **enforces** the backup label _cluster.open-cluster-management.io/backup: msa_ on auto-import-account secrets found in managed cluster namespaces other than local-cluster
https://issues.redhat.com/browse/ACM-7850
Add any additional notes, context, or information that might be helpful …

New policy to report issues related to backup restore auto import configs

---

pkg/templates/charts/toggle/grc/templates/grc-policy-addon-clusterrole.yaml
pkg/templates/charts/toggle/grc/templates/grc-policy-compliance-history-api-service.yaml
pkg/templates/charts/toggle/grc/templates/grc-policy-propagator-deployment.yaml

The compliance history API is not exposed outside of the cluster by default. The governance-policy-addon-controller handles creating a Route when the governance-policy-database Secret is defined.
Relates:
https://issues.redhat.com/browse/ACM-6870

Add support for the policy compliance history API

---

pkg/templates/charts/toggle/grc/templates/grc-policy-addon-clusterrole.yaml

This syncs the RBAC changes from this:
https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/133
Relates:
https://issues.redhat.com/browse/ACM-6889

Add permissions to the GRC addon controller for compliance history

---

pkg/templates/charts/toggle/console/templates/console-deployment.yaml
pkg/templates/charts/toggle/console/values.yaml

This PR provides template-override capability for  console deployment cpu/memory requests and limits.  Four template-override keys are defined, one for each:
- `console_deployment_container_memory_request`
- `console_deployment_container_cpu_request`
- `console_deployment_container_memory_limit`
- `console_deployment_container_cpu_limit`
These template overrides can be defined using the mechanisms being implemented by PR #1333 .
If no template overrides are defined, the updated chart produces the same deployment as it does prior to this PR.  
- Add default (empty) global.templateOverrides to value.yaml (with comments aboute available overrides)
- Update console-deployment.yaml to use cpu/memory request and limit overrides if they are found to have been defined as …

Enable template overrides for console cpu/memory requests and limits

---

test/unit-tests/crds/cluster_management_addons.yaml

The MCH unit tests use a "private" copy of various ACM CRDs, stashed in the `test/unit-tests/crds` directory of this repos.  Because they are a manually-updated copy, they can get old relative to evolution of the CRDs.  That usually isn't a problem (its just unit tests after all) until we find that Charts start to contain resource definitions for CRs that use new properties etc. not value in the copy of the CRD we have stashed for our unit testing.
In particular, we've seen issues related to use of the `installStrategy` property of the `ClusterManagementAddOn` CRD, including a problem brewing today for a recent bundle-update run.  This PR addresses that particular problem by updating the CMA CRD to match the copy currently in the `manifests/cluster-manager/hub` directory of the …

Update the CMA CRD being used for unit tests

---

pkg/templates/crds/grc/policy.open-cluster-management.io_placementbindings.yaml
pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml
pkg/templates/crds/grc/policy.open-cluster-management.io_policyautomations.yaml
pkg/templates/crds/grc/policy.open-cluster-management.io_policysets.yaml

There will be skew between the hub and managed clusters since the managed cluster CRDs are being built with controller-gen v0.6.1, but it shouldn't cause issues since the differences are in the multiline `description` strings.
ref: https://issues.redhat.com/browse/ACM-9975
/cc @mprahl @JustinKuli @yiraeChristineKim @gparvin

Sync the GRC CRDs

---

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-auto-import.yaml

When ManagedServiceAccount feature is not enabled on MultiClusterEngine, the policy template encounters error calling lookup: one or more API resources are not installed on the API server.
https://issues.redhat.com/browse/ACM-10214
Before looping through ManagedServiceAccount instances, get the MultiClusterEngine cluster scoped instance and check whether managedserviceaccount component is enabled

Fix policy template unknown API issue when ManagedServiceAccount is not enabled

---

pkg/templates/charts/toggle/grc/templates/grc-policy-addon-clusterrole.yaml

This will remove the log errors of:
controller failed to sync "governance-policy-framework", err: clustermanagementaddons.addon.open-cluster-management.io "governance-policy-framework" is forbidden: User "system:serviceaccount:open-cluster-management:grc-policy-addon-sa" cannot patch resource "clustermanagementaddons/status" in API group "addon.open-cluster-management.io" at the cluster scope

GRC: Add missing permissions on the grc-policy-addon SA

---

Makefile

the controller runtime setup-envtest tool is not versioned the same way that controller-runtime itself is, and the contributors updated its @latest tag to require go1.22. The Makefile has been updated to grab a specific release branch instead to avoid this issue.
Here is a reference issue on the controller-runtime repo that suggests this workaround until they can version that tool separately: https://github.com/kubernetes-sigs/kubebuilder/issues/2480#issuecomment-1825529490

Controller runtime tool versioning fix

---

api/v1/multiclusterhub_methods.go
api/v1/multiclusterhub_methods_test.go
api/v1/multiclusterhub_types.go
bundle.Dockerfile
bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml
bundle/metadata/annotations.yaml
config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml
config/manager/manager.yaml
config/manifests/bases/multiclusterhub-operator.clusterserviceversion.yaml

The integer type in the crd spec actually is fine, because the enum type in the codebase is using an integer. The CRD still allows the enum and defaults.

Fully qualified hubSizes and generated bundles

---

pkg/templates/charts/toggle/cluster-backup/templates/backup-pvc-source.yaml

Update ReplicationSource configmap properties to include all optional properties
https://issues.redhat.com/browse/ACM-10837
- Added these optional properties to the `hub-pvc-backup` ConfigMap
spec.restic.volumeSnapshotClassName
spec.restic.customCA
Missing but less important:
spec.restic.capacity
spec.restic.storageClassName
spec.restic.accessModes
spec.restic.cacheStorageClassName
spec.restic.cacheAccessModes
- updated the ReplicationSource template to use the `mustonlyhave` compliance type so that optional properties which are removed from the configMap are also removed from the ReplicationSource
Tag the appropriate reviewers …

update configmap with optional properties

---

pkg/templates/charts/toggle/cluster-backup/templates/backup-pvc-destination.yaml

Allow overwriting PVC attributes on restore
https://issues.redhat.com/browse/ACM-10763
Support updating PVC and ReplicationDestination attributes when the PVC is restored:
- Introduced the hub-pvc-restore/open-cluster-management-backup  ConfigMap as an optional resource that can be defined by the user on the hub where the PVC is being restored.
If this ConfigMap is to be used for a restore operation, the hub-pvc-restore ConfigMap must be created under the open-cluster-management-backup namespace before the ACM Restore.cluster.open-cluster-management.io resource is created, so before the backup-pvc-destination policy starts creating the PVC resource.
The hub-pvc-restore ConfigMap is in this format:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
name: hub-pvc-restore
namespace: …
```

overwrite restore PVC attributes

---

pkg/templates/charts/toggle/cluster-backup/templates/backup-pvc-destination.yaml
pkg/templates/charts/toggle/cluster-backup/templates/backup-pvc-source.yaml

remove repository option and use capacity for PVC and RDest
https://issues.redhat.com/browse/ACM-10763
- Removed the repository option from the hub-pvc-backup ConfigMap. This option was used to allow the user setting the name of the restic secret when copied over to the PVC ns ( backup or restore scenario ). The name of this secret is now defaulted to pvc_name-acm-pvc-restic.
- Used capacity for both PVC and RDest on restore. This is a property defined by the user with the optional hub-pvc-restore ConfigMap. If defined, it will overwrite the PVC resources.requests.storage property set on the original PVC and stored by the hub-pvc-backup-pvc_name / pvc_ns ConfigMap
Add any additional notes, context, or information …

remove repository option and use capacity for PVC and RDest

---

pkg/templates/charts/toggle/cluster-backup/templates/backup-pvc-destination.yaml
pkg/templates/charts/toggle/cluster-backup/templates/backup-pvc-source.yaml

Support updating RDest properties on restore
https://issues.redhat.com/browse/ACM-10763
- hub-pvc-restore-pvc_ns_pvc_name (pvc - specific configmap at restore time) should not merge with the global hub-pvc-restore configmap.  This is the same behaviour as at backup time.  That is, users who specify the pvc specific configmap need to set everything they want there.  These values will override the automatic settings backed up by the policy.
volumeMode doesn't need to be backed up 
- VolSync with restic only supports backing up PVCs with volumeMode: `Filesystem`.  Removed the volumeMode from configmap and hardcoded to Filesystem. 
- added a new policy template `check-hub-pvc-filesystem` on source policy to validate that any PVC with the backup label has the  volumeMode set to `Filesystem`
- …

add restore ovw properties

---

pkg/templates/charts/toggle/cluster-backup/templates/backup-pvc-destination.yaml
pkg/templates/charts/toggle/cluster-backup/templates/backup-pvc-source.yaml

make restic secret configurable on restore
https://issues.redhat.com/browse/ACM-11003
- Update `backup-pvc-destination` to look for a `acm-hub-pvc-restore-restic-secret` Secret in the `open-cluster-management-backup`. If this secret exists, it will be used instead of the `acm-hub-pvc-backup-restic-secret` 
- Updated `backup-pvc-source` Policy to hardcode the ReplicationSource copyMethod to Snapshot

support restore from a different location than the backup

---

pkg/templates/charts/toggle/cluster-backup/templates/backup-oadp-config.yaml
pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-policy-set.yaml
pkg/templates/charts/toggle/cluster-backup/templates/managed-hub-policy-set.yaml

Create a policy to wrap up the installation of the oadp operator
https://issues.redhat.com/browse/ACM-10890
Created a new Policy which can be used to install OADP.
The policy does not install  OADP if 
- this is an STS enabled cluster
- the user sets oadp-manual=true label on the local-cluster hub resource
In the screen cap below, the  oadp-manual=true label is set on the local-cluster hub resource so the policy doesn't try to create the operator
The policy is disabled for now and I am keeping the chart resources used to install the OADP operator; once I can test the policy being packaged with the chart I will enable it and replace the chart resources
Tag the appropriate reviewers who should review this …

policy to install oadp

---

pkg/templates/charts/toggle/cluster-backup/templates/backup-oadp-config.yaml

Enable the policy used to install OADP
https://issues.redhat.com/browse/ACM-11015
- Updated oadp-policy and enable it
```
spec:
disabled: false
```
- Fixed extra spaces on the tolerations section which makes the policy engine throw a wrapping error

enable oadp install policy

---

pkg/templates/charts/toggle/cluster-backup/templates/backup-oadp-config.yaml

Trigger oadp policy deletion when chart is uninstalled. This should delete the OADP subscription resource so that a new version of OADP can be installed on upgrade
https://issues.redhat.com/browse/ACM-11015
Updated oadp-install policy and added 
```
"helm.sh/hook": pre-install, post-delete
"helm.sh/hook-weight": "-1"
"helm.sh/resource-policy": delete
```

trigger oadp policy deletion when chart is uninstalled

---

Makefile
Makefile.dev
test/function_tests/Makefile

For Red Hat, there was an announcement made for us to use `podman` instead of `docker`; therefore, this PR will add the support for `podman` and keep the `docker` compatibility if it is still needed.
https://issues.redhat.com/browse/ACM-10819
Added supported `podman` configs in the Makefiles.

[ACM-10819] Updated Makefiles to support podman configuration

---

pkg/utils/annotations.go

Updated MCH annotations to use `installer.<annotation>` pattern, instead of `operator.<annotation>` pattern.
https://issues.redhat.com/browse/ACM-10802
Updated MCH annotations names.

[ACM-10802] Updated MCH annotations naming convention

---

api/v1/multiclusterhub_methods.go
controllers/common.go
controllers/multiclusterhub_controller.go

When attempting to remove the CMA for GRC, we are removing it before MCE is ready and has deployed the CMA CRD. This is preventing the MCH operator from deploying fully.
https://issues.redhat.com/browse/ACM-11398
Updated removal order for GRC CMA.

[ACM-11398] Updated MCH operator to remove GRC CMA after MCE deployed

---

pkg/templates/charts/toggle/volsync-controller/templates/volsync-addon-controller-clusterrole.yaml

Required for addon-framework updates
For: https://issues.redhat.com/browse/ACM-10539
Volsync-addon-controller update clusterrole to allow "patch" for clustermanagementaddon resources.  The addon-framework now does a patch to the clustermanagementaddon to update an annotation.
Note this should also go into release-2.10 as this change in the addon-framework was made back in v0.8.1 which is used in release-2.10.

Volsync-addon-controller update clusterrole https://issues.redhat.com/browse/ACM-10539

---

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml

Add a new ACM policy template to verify if OADP is installed
https://issues.redhat.com/browse/ACM-11018
Added a new ACM policy template to verify if OADP is installed in open-cluster-management-backup namespace

ACM-11018 - OADP operator should exist in open-cluster-management-backup ns

---

bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml
hack/bundle-automation/generate-shell.py

For this release, we migrated the usage of the hubSize field to an annotation; therefore, we don't need to display it within the CRD spec field.
https://issues.redhat.com/browse/ACM-11364
Removed `HubSize` from MCH CRD.

[ACM-11364] Removed hubSize reference from CRD

---

api/v1/multiclusterhub_methods.go
controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
controllers/status.go
controllers/status_test.go
pkg/templates/rbac_gen.go
pkg/utils/utils.go
pkg/utils/utils_test.go

When ACM is awaiting for an MCE sub-component's CRD to be created we are currently throwing an error status which is giving off the appearance that something is broken within the cluster very early; however, this is not the case. This change will ignore the CR instance creation until the CRD is present on the cluster.
https://issues.redhat.com/browse/ACM-11156
Add logic to support missing MCE sub-component's CRD toleration.

[ACM-11156] Updated MCH to tolerate if a MCE CRD is missing

---

controllers/common.go

Adds a label to the Search CR to enable backup.
https://issues.redhat.com/browse/ACM-9668
Adds a label to the Search CR to enable backup, based on documentation here: [https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for[…]ernetes/2.10/html/business_continuity/business-cont-overview](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.10/html/business_continuity/business-cont-overview#resources-that-are-backed-up)
Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @reviewer1 …

[ACM-9668]: Add backup label to Search CR

---

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml

Revisit templates checking OADP version
https://issues.redhat.com/browse/ACM-11855
Added policy templates to check for the following:
- The oadp-operator-exists template checks that an OADP subscription exists in the open-cluster-management-backup namespace.
- The oadp-channel-validation template checks that the OADP installed in the open-cluster-management-backup namespace matches the chart version or has a newer version.
- The custom-oadp-channel-validation template checks that any OADP installed in any namespace matches the version of OADP in the open-cluster-management-backup namespace.
Tag the appropriate reviewers who …

ACM-11855 - Revisit OADP operator policy templates

---

hack/bundle-automation/generate-shell.py

Changing the repository path back to `stolostron`. It is currently pointing towards a forked repository.

Revert shell script org to stolostron

---

api/v1/multiclusterhub_types.go
bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml
config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml
controllers/status.go
controllers/status_test.go

Enhanced the MCH component status to include `name` and `kind`. This PR will also add additional logging to show when a component within MCH is not available.
```yaml
multicluster-engine-csv:
kind: ClusterServiceVersion
lastTransitionTime: '2024-06-07T16:39:07Z'
message: install strategy completed with no errors
name: multicluster-engine.v2.6.0
reason: InstallSucceeded
status: 'True'
type: Available
```
```
2024-06-07T11:49:06.668Z INFO reconcile The component is now available. {"Kind": "MultiClusterEngine", "Name": "multiclusterengine"}
```
https://issues.redhat.com/browse/ACM-11732
Add any additional notes, context, or information …

[ACM-11732] Enhance available component statuses

---

.github/workflows/regenerate-sha-commit.yml

Added support for Personal Access Token (PAT) for the regenerate sha commit script. When pulling from a private  repository, you need to provide a token for the github action to clone the private repository.
Added `env` for `GH_READ_PAT` for `regenerate-sha-commit` script.

Added PAT support for regenerate-sha-commit script

---

api/v1/multiclusterhub_types.go
bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml
config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml

Added `currentVersion` and `desiredVersion` to the `additionalPrinterColumns` in MCH CRD.
https://issues.redhat.com/browse/ACM-12430
Added support to print out the `currentVersion` and `desiredVersion` of the MCH operator.

[ACM-12430] Added MultiClusterHub current and desired version columns to MCH CRD

---

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-placementrule.yaml

Support hub policy to run on a hub with name changed from local-cluster
https://issues.redhat.com/browse/ACM-12881
In the existing PlacementRule, instead of checking the label name=local-cluster, look for the label local-cluster=true to identify the local cluster, no need to check the name, because the local-cluster=true label has been added for several releases, could not bring backward compatibility issue. 

ACM-12881 - Support customizing local cluster name

---

pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_restores.yaml

The user should be able to filter restore resources using velero restore options
https://issues.redhat.com/browse/ACM-12973
Updated CRD for restores.cluster.open-cluster-management.io to include 
includedResources
includedNamespaces
LabelSelector
OrLabelSelector

update CRD to include user restore options

---

pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_backupschedules.yaml

update BackupSchedule CRD using velero 1.13.2 libs
Related to https://github.com/stolostron/cluster-backup-operator/pull/709
https://issues.redhat.com/browse/ACM-13001
Updated BackupSchedule CRD

ACM-13001 - update BackupSchedule CRD using latest velero

---

pkg/utils/utils.go

Site config was previously missing from the list of deployments to be checked in the status check
https://issues.redhat.com/browse/ACM-13731
Added site config the list of conditionals in the function `ListDeploymentsForStatus`

 Add site config to the list of deployments for status

---

Makefile
config/rbac/role.yaml
controllers/multiclusterhub_controller_test.go
controllers/suite_test.go
pkg/templates/charts/toggle/console/templates/acm-cli-consoleclidownload.yaml
pkg/templates/charts/toggle/console/templates/acm-cli-deployment.yaml
pkg/templates/charts/toggle/console/templates/acm-cli-route.yaml
pkg/templates/charts/toggle/console/templates/acm-cli-service.yaml
pkg/templates/rbac.go
pkg/templates/rbac_gen.go
pkg/utils/utils.go
test/unit-tests/crds/consoleclidownloads.yaml
test/unit-tests/crds/route.yaml
test/unit-tests/crds/search.yaml

Add an `acm-cli` chart to add a plugin to download CLIs from the OCP console.
https://issues.redhat.com/browse/ACM-12551
Adds a new chart with Deployment, Route, Service, and ConsoleCLIDownload manifests to deploy the `acm-cli` image. The image is a Golang HTTP server that serves the files made available in the console via the ConsoleCLIDownload plugin.
--

Add `acm-cli` console CLI download

---

controllers/common.go
main.go

In #1447 we updated the functionality around getting the `packagemanifest` and determining the `catalogsource` based on `priority`. Within that PR we changed one of the funcs for using an `uncachedClient` to a regular `client`, which caused the operator to fail when trying to verify the `packagemanifests` and `catalogsource`. This is because the regular client will automatically try to watch resources; however, `packagemanifests` do not support `watch` for it's API group. 
https://issues.redhat.com/browse/ACM-10559
Updated client to disable caching for `packagemanifest` resources.
Tag the appropriate reviewers who should review …

[ACM-10559] Updated client to disable caching for packagemanifests

---

controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
main.go

When the MCH resources are being finalized upon uninstall, there was a possibility for the `clusterRoles` and `clusterRoleBindings` resources to be removed before the MCH operands could clean up any finalizers or other resources. This PR will add another condition to check if there was a requeue result returned, then re-reconcile.
https://issues.redhat.com/browse/ACM-15080
Added requeue result condition for finalizing hub resources.

[ACM-15080] Updated requeue logic for finalizing resources

---

main.go

When a user has a large cluster with a lot of operator running, there is a chance where the MCH operator will hit a limit when caching the `ClusterServiceVersion` resources. This PR will disable the caching for the CSV resources. Since we only need to get the MCE CSV resource, we can disable caching and watching for all CSV resources under the covers.
```bash
W1107 17:45:46.730207 1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1alpha1.ClusterServiceVersion: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 23079; INTERNAL_ERROR; received from peer
E1107 17:45:46.730257 1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed …
```

[ACM-15448] Updated client to disable caching for ClusterServiceVersion resources

---

controllers/common.go
controllers/finalizers.go
controllers/multiclusterhub_controller_test.go
controllers/status_test.go

When we disabled the caching for the `ClusterServiceVersion` resource, that caused issues when attempting to convert the MCE resource to a `unstructured.unstructured{}` resource. The issue that was occurring was that the `Kind` and `ApiVersion` of the resource were being dropped due to the resource being uncached. To resolve this, we can use the kube scheme that our operator registers during runtime to handle the conversion.
https://issues.redhat.com/browse/ACM-15851
Update MCE CSV conversion func.
Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @reviewer1 …

[ACM-15851] Updated MCE CSV conversion to use reconciler scheme convert

---

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml
pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml

There is an issue with the DataUploader on restore if velero is installed in a different namespace on the backup cluster vs restore cluster. There is a workaround provided by the OADP team for that, added this here ; https://redhat-internal.slack.com/archives/C0144ECKUJ0/p1736274571133809?thread_ts=1736269804.273929&cid=C0144ECKUJ0
Also fixed the backup annotation for vmuid if more than one vm is backed up
Updated restore policy and added a namespaceMapping
Updated Backup policy and fixed the vmUId parse when multiple vms are backed up by the same schedule
Tag the appropriate reviewers …

fix DataUploader ns and Backup vmUID annotations

---

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml

Cleanup oadp csv created by the policy, when the policy is reapplied. The issue : if the user applies the policy, OADP is installed in the specified namespace. If the namespace already exists ( so is not going to be deleted when the policy is removed ), then only the Subscription and OperatorGroup resources are being cleaned up. The CSV is created by the Subscription, so not by the policy, and as a result it will remain after the policy is removed from the managed cluster.
Next time the policy is placed on the same managed cluster, the OADP install fails because there is already a csv in that ns.
The fix 
- tag the CSV created by the Subscription with an annotation, `cluster.open-cluster-management.io/ownSubs: subscriptionUID` , when the Subscription is created
- delete any OADP csv using …

tag and cleanup csv's when policy is installed

---

controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
pkg/rendering/renderer.go

 add logic to get open shift API URL

---

controllers/common.go
controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
controllers/status.go
controllers/uninstall.go

After merging this PR: https://github.com/stolostron/multiclusterhub-operator/pull/1882, a regression was introduced that affected ACM version upgrades. This new PR aims to resolve the issue and enable successful upgrades.
https://issues.redhat.com/browse/ACM-16805
Removed setting the template ManagedFields to nil:
```go
template.SetManagedFields(nil)
```

[ACM-16805] Fixed regression for template resource patching

---

controllers/multiclusterhub_controller.go

It was possible for the controller to be stuck in a loop, unable to render the charts when the MCH was deleted, because some default values had not been set. This situation would likely only occur if the controller was not running when the MCH was first deleted.
This is a small bugfix that came up while debugging around a "stuck" uninstallation scenario. I encountered this scenario by starting a new instance of the controller (with changes) after the MCH resource was deleted.
Add any additional notes, context, or information that might be helpful for …

Ensure defaults are set before finalizing hub

---

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml
pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml

Replace policy dependency with a policy compliance check.
Backup and restore policies are dependent on the install policy, which means these policies are disabled every time the install policy has a violation. This is an issue because let's say the restore policy might be in the process of restoring data while the install policy has a violation; as a result, the restore policy is disabled and the velero restore is deleted.
Removed dependant section for the backup and restore policies. They no longer depend on the install policy.
Updated the create-velero-restore template to run only if the install policy is compliant.
Updated thecreate-virt-backup template to run only if the install policy is compliant.
Add screenshots or GIFs that demonstrate …

replace policy dependency with a policy compliance check

---

.tekton/multiclusterhub-operator-pull-request.yaml
.tekton/multiclusterhub-operator-push.yaml
hack/bundle-automation/chart-values/managed-serviceaccount/values.yaml

Updated the `.tekton` push file to include an `IMAGE` value for the `sast-coverity-check-oci-ta` step. This field is needed after the recent migration.
```
[User error] Validation failed for pipelinerun multiclusterhub-operator-on-push-klgtb with error invalid input params for task sast-coverity-check-oci-ta: missing values for these params which have no default values: [IMAGE] 
```
https://github.com/stolostron/multiclusterhub-operator/pull/1947
Update `.tekton` file. …

Updated .tekton push sast-coverity-check-oci-ta config to include IMAGE value

---

pkg/templates/charts/toggle/volsync-controller/templates/volsync-addon-controller-deployment.yaml

volsync-addon-controller will need to look at the mch image manifest configmap, and would like to restrict the search to the mch namespace, that is, the namespace of the volsync-addon-controller pod itself.
Update is to use the downward api to pass in POD_NAMESPACE to the volsync-addon-controller in the deployment.yaml
https://issues.redhat.com/browse/ACM-16311

POD_NAMESPACE env var in volsync-addon-controller

---

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml
pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml
pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml

Allow setting the startingCSV for the OADP install.
Remove check for install policy compliance and check required configMaps instead, to avoid cleaning up restore or schedule resources when the install policy is non compliant.
Updated install policy and included the startingCSV prop for the oadp subscription.
Removed the install compliance policy check from the backup and restore policies; replaced that with required configMaps check instead.

remove install policy check and use startingCSV

---

pkg/templates/charts/toggle/grc/templates/grc-policy-addon-clusterrole.yaml
pkg/templates/charts/toggle/grc/templates/standalone-hub-templates-clustermanagementaddon.yaml

Refs:
- https://issues.redhat.com/browse/ACM-16091
Adds permissions to the GRC role for its new (optional, off-by-default) addon, as well as that addon's CMAO.
https://issues.redhat.com/browse/ACM-16088
Adds some permissions and a ClusterManagementAddOn resource.

Add permissions for standalon-hub-templates addon

---

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml

When looking for backups with a startTimestamp, get only backups created by this cluster.
There are cases when backups are created on different clusters using the same virt schedule name, so they may have the same timestamp. When checking the status of the latest backup, get only backups created by this cluster.
Updated check-backup-status-completed template to get only backups that have the label cluster.open-cluster-management.io/backup-cluster=cluster_version , where cluster_version is the clusterId for the current cluster
Tag the appropriate reviewers who should review this pull …

get only backups created by this cluster

---

controllers/multiclusterhub_controller.go

Currently, when a CRD fails to deploy in ACM, we do not return the actual error from the client. Instead, we generate and return a custom error. This PR will update the error logging to capture the actual failure from the client.
```
2025-02-19T21:44:27.202Z ERROR reconcile failed to deploy {"Kind": "CustomResourceDefinition", "Name": "policyreports.wgpolicyk8s.io", "error": "CustomResourceDefinition.apiextensions.k8s.io \"policyreports.wgpolicyk8s.io\" is invalid: status.storedVersions[0]: Invalid value: \"v1beta1\": must appear in spec.versions"}
```
https://issues.redhat.com/browse/ACM-17509
Updated `installCRDs` func to better capture error log.
Add any additional notes, context, or information that might be …

[ACM-17509] Updated installCRDs func logs to include err

---

pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_backupschedules.yaml

Update backupschedule CRD to align with Velero 1.14 API
https://github.com/stolostron/cluster-backup-operator/pull/893
Update backupschedule CRD to align with Velero 1.14 API

Update backupschedule CRD to align with Velero 1.14 API

---

controllers/multiclusterhub_controller.go

During ACM installation, MCH will try to deploy specific resource types created during the MCE standup. If the corresponding CRDs are missing from the cluster, we only log which CRD is unavailable but do not capture the resource name. This PR will include the name of the template resource being applied during runtime in the log.
```
2025-02-20T14:01:13.096Z INFO reconcile CustomResourceDefinition does not exist. Skipping resource creation {"Group": "addon.open-cluster-management.io", "Version": "v1alpha1", "Kind": "ClusterManagementAddOn"}
```
Updated missing CRD logging.
Add any additional notes, context, or information that might be …

Added template resource name for missing MCE CRD log

---

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-backup.yaml
pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml
pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml
pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml

Allow updating acm-dr-virt-config properties after the ConfigMap is created by the policy
https://issues.redhat.com/browse/ACM-18090
- Updated vm-config-setup template to attempt to create the acm-dr-virt-config ConfigMap only when the maps are first created. Allow this way for the user to update the ConfigMap after initial creation ( the policy is not going to try to reconcile the policy after its creation )
- Updated temporary configmap names for the ConfigMap created on the managed clusters from the hub resources. Easier to map them back to the initial ConfigMap from where they were originated. The name is also hard to be overwritten by user by mistake ( used --cls ) as a suffix for the copied ConfigMap name …

allow updating acm-dr-virt-config props

---

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml

Related to https://github.com/stolostron/multiclusterhub-operator/pull/2031
When checking if the config needs to be created, look for the acm-dr-virt-config configmap instead of acm-dr-virt-schedule-cron. In this way, only when the acm-dr-virt-config configmap is deleted, it gets recreated.
https://issues.redhat.com/browse/ACM-18090
Updated vm-config-setup template to check for  acm-dr-virt-config configmap instead of acm-dr-virt-schedule-cron

look for acm-dr-virt-config instead of acm-dr-virt-schedule-cron

---

hack/bundle-automation/config.yaml
pkg/templates/charts/toggle/siteconfig-operator/templates/clusterinstances.siteconfig.open-cluster-management.io-validatingwebhookconfiguration.yaml

To ensure the SiteConfig operator starts up correctly, we need to deploy the webhook resource in ACM 2.13 and 2.14. In this PR, we've updated our automation config to retrieve the `validatingwebhookconfiguration` for their component, enabling MCH to deploy it during runtime.
https://issues.redhat.com/browse/ACM-18309
Updated `hack/bundle-automation/config.yaml` to include webhook path for SiteConfig component.

[ACM-18309] Added ValidatingWebhookConfiguration for siteconfig

---

controllers/status.go

In MCH, when reporting the status of the MCE subscription during an `UpgradePending` scenario, the `installedCSV` and `currentCSV` values are displayed in the incorrect order, which leads to confusion for end users. This PR will correct the order in which these values are referenced, ensuring clarity in the status message.
```yaml
multicluster-engine-sub:
kind: Subscription
lastTransitionTime: '2025-03-14T16:00:38Z'
message: 'Upgrade pending. Installed CSV: multicluster-engine.v2.6.6. Pending CSV: multicluster-engine.v2.6.5'
name: multicluster-engine
reason: UpgradePending
status: 'True'
type: Available 
```
```yaml
multicluster-engine-sub:
kind: Subscription
lastTransitionTime: '2025-03-14T16:00:38Z'
message: 'Upgrade pending. Installed CSV: multicluster-engine.v2.6.5. Pending CSV: …
```

[ACM-18906] Updated MCH status for MCE subscription to reflect correct upgrade pending message

---

pkg/templates/charts/toggle/console/templates/console-plugin.yaml

OpenShift console will start reporting Content Security Policy violations with version 4.19
ACM needs to declare that it will access the GitHub API for listing branches and paths in respositories when deploying applications.
https://issues.redhat.com/browse/ACM-17765
Added new configuration to the `ConsolePlugin` resource which should be ignored on older releases.

Add CSP directive for GitHub API access

---

controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go
pkg/rendering/renderer.go
pkg/utils/annotations.go
pkg/utils/annotations_test.go

Setting a custom storage class name for StatefulSet and PersistentVolumeClaim resources through an environment variable (DEFAULT_STORAGE_CLASS_NAME) is not working as expected. The default storage class name always takes precedence, overriding any custom setting, and leading to StatefulSet resources application failure.
This PR will add the missing logic for the StatefulSet resources and ensure that the environment variable that is set is not getting overridden.
https://issues.redhat.com/browse/ACM-19115
Updated storage class name logic in the operator controller.
Tag the appropriate reviewers who should review this pull …

[ACM-19115] Improved storage class name handling for PVC and StatefulSet resources

---

pkg/rendering/renderer.go
pkg/rendering/renderer_test.go
pkg/templates/charts/toggle/cluster-backup/values.yaml

Annotation `installer.open-cluster-management.io/oadp-subscription-spec` now accepts `startingCSV`

startingCSV can now be set via annotation

---

hack/bundle-automation/charts-config.yaml

In ACM 2.14, our automation has detected that `edge-manager` needs the following image keys added to the `imageMapping`:
- `flightctl-cli-artifacts`
- `origin-cli`
- `redis-7-c9s`
https://issues.redhat.com/browse/ACM-19712
Updated `imageMapping` for `edge-manager`.

[ACM-19712] Updated charts-config imageMapping for Edge Manager

---

hack/bundle-automation/charts-config.yaml

In ACM 2.13 our automation has detected that `edge-manager` needs the following image keys added to the `imageMapping`:
- `origin-cli`
- `redis`
https://issues.redhat.com/browse/ACM-19713
Updated `imageMapping` for `edge-manager`.

[release-2.13][ACM-19713] Updated charts-config imageMapping for edge-manager

---

pkg/utils/utils.go

As we onboard new image keys into MCH or MCE, it's important to make sure they are added to the `testImages` map so we can properly render resources in both `dev` and `prod` environments.
https://issues.redhat.com/browse/ACM-19712
https://github.com/stolostron/multiclusterhub-operator/pull/2127
Updated `testImages` map to include new image keys.

Updated test images references to include new Edge Manager images

---

pkg/rendering/renderer.go
pkg/rendering/renderer_test.go
pkg/rendering/values.go

When deploying ACM 2.14 on OCP 4.19, only the OADP `stable-1.5` channel is supported. As a result, we had to update our render functionality to allow selecting the appropriate channel for OCP 4.19.
https://issues.redhat.com/browse/ACM-19914
Updated `renderer.go` file.

[ACM-19914] Updated chart render to support OADP stable-1.5 channel for OCP 4.19

---

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-install.yaml
pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml

Update virtualization policy to install OADP based on the ocp version. 
https://issues.redhat.com/browse/ACM-19866
Updated `vm-config-setup` template to not setup the oadp channel by default. The channel will now be set based on the ocp version.
Updated the `acm-dr-virt-install` policy to set the oadp channel based on the ocp version, if the oadp version is not set by the user with the configmap

add support for ocp 4.19 on virt policies

---

hack/bundle-automation/charts-config.yaml

Added `security-context-constraints` to `flight-control` chart to ensure that the `flightctl-db` deployment is not overridden for `readOnlyRootFilesystem`.
https://issues.redhat.com/browse/ACM-18824
Added `security-context-constraints` to `flight-control` config.

[ACM-18824] Added security-context-constraints override to flight-control chart config

---

pkg/templates/charts/toggle/cluster-backup/templates/acm-dr-virt-restore.yaml

Allow restoring a vm in a different namespace
https://issues.redhat.com/browse/ACM-19860
Updated restore operation 
- restore-config ConfigMap has a new optional property that can be used to provide a ns mapping for a cluster restore action: `clusterID_namespaceMapping: backup-ns-1=restore-ns-1 backup-ns-2=restore-ns-2`
- updated the restore policy to create a `namespaceMapping:` spec section if above is present

support restoring a vm in a different ns

---

pkg/rendering/renderer.go
pkg/rendering/values.go
pkg/templates/charts/toggle/cluster-backup/templates/odap-operator-pre-install-hook.yaml
pkg/templates/charts/toggle/cluster-backup/values.yaml

OADP annotation should overwrite chart settings when using OCP 4.19 or higher
https://issues.redhat.com/browse/ACM-20211
- Created a new var minOADPStableChannel = stable
- Updated func GetOADPConfig and if the channel is not set, use minOADPStableChannel if ocp version is 4.19 or newer
- Removed channel from the backup chart values.yaml to get the default value, based on ocp version
- On the subscription, set 
```
spec:
channel: {{ .Values.global.channel }}
```

set defaults for oadp stable channel

---

Makefile
api/v1/multiclusterhub_webhook.go
api/v1/multiclusterhub_webhook_test.go

When updating spec.LocalClusterName, if local-cluster resource already exists, the update will be blocked.

[ACM-20060]: modify validateUpdate() to block renaming local-cluster if the resource already exists

---

controllers/common.go
controllers/multiclusterhub_controller.go
controllers/multiclusterhub_controller_test.go

When upgrading from ACM 2.12, a new label selector was added to deployment/siteconfg-controller-manager, which is an immutable field. The deployment must be deleted before the patch can be applied

[ACM-20337] ACM 2.12 upgrade to 2.13 siteconfig-controller-manager deployment temporary deletion

---

Makefile
api/v1/multiclusterhub_webhook.go
api/v1/multiclusterhub_webhook_test.go

Through speaking with other teams and QE, it seems that exceeding 39 characters in length (yes 39, not 34) will cause ACM installed components to fail due to how components tack on information to existing resource names, causing them to exceed the Kubernetes allowed 63 character limit. The 34 character limit is to make sure that we don't get close to that number.
Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following …

Prevent local-cluster name from exceeding 34 characters

---

pkg/rendering/renderer.go
pkg/rendering/renderer_test.go
pkg/rendering/values.go
pkg/templates/charts/toggle/cluster-backup/templates/odap-operator-pre-install-hook.yaml
pkg/templates/charts/toggle/cluster-backup/values.yaml

Updating the `cluster-backup` chart to support `channel15` for OCP 4.19 and later has introduced issues during deployment, causing the `cluster-backup` component to stall during installation on the cluster. This PR will fix the issue and allow for `cluster-backup` to be deployed properly.
https://issues.redhat.com/browse/ACM-20703
Updated `cluster-backup` chart.
/cc @cameronmwall @ngraham20 
/hold

[ACM-20703] Set defaults for OADP stable channel 

---

build/Dockerfile.rhtap

To support `multi-arch` builds, this PR removes the hardcoded architecture reference from `build/Dockerfile.rhtap`, enabling flexible image builds across different platforms.
https://issues.redhat.com/browse/ACM-20954
Removed `GOOS=linux GOARCH=amd64` reference from `build/Dockerfile.rhtap`.

[ACM-20954] Removed hardcoded ARCH for Dockerfile.rhtap

---

controllers/common.go
controllers/multiclusterhub_controller.go

The label selectors can't be applied as a template if the original exists. The original must be deleted first.

ACM-20337 Can't create ClusterInstance after upgrading from 2.12.x to 2.13.3

---

hack/bundle-automation/charts-config.yaml
pkg/templates/charts/toggle/flight-control/templates/flightctl-cli-artifacts-deployment.yaml

During testing of ACM 2.14, we observed that the `flightctl-cli-artifact` deployment in EM failed to start with the following error:
```bash
/usr/local/bin/entrypoint.sh: line 16: /tmp/index.json: Read-only file system
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (30: Read-only file system)
2025/06/10 17:44:25 [emerg] 1#1: mkdir() "/var/lib/nginx/tmp/client_body" failed (30: Read-only file system)
```
To fix this, the `readOnlyRootFilesystem` setting must be set to `false` in the deployment for the CLI tool.
`readOnlyRootFilesystem` was disabled for the `flightctl-cli-artifact` deployment in the `flight-control` chart.
Add screenshots or GIFs that demonstrate the …

[manual] Chart Update [main]

---

pkg/templates/charts/toggle/console/templates/console-plugin.yaml

Bug in CSP implementation in OpenShift 4.19.0 means we should only enable the feature for 4.19.1
https://issues.redhat.com/browse/OCPBUGS-55928
https://issues.redhat.com/browse/ACM-21533
Update version for conditional rendering of CSP in ACM ConsolePlugin resource to 4.19.1 from 4.19.0

ACM-21533 Require 4.19.1 due to OpenShift console crash on 4.19.0

---

controllers/multiclusterhub_controller.go

During the MCH operator upgrade, the logs that check release versions mistakenly print the resource's `Kind` instead of its `Name`. This PR will correct those logs.
```bash
2025-06-17T18:53:11.144Z INFO reconcile Resource version mismatch detected; attempting to update resource {"Kind": "hypershift-addon", "Name": "ManagedClusterAddOn", "CurrentVersion": "2.8.2", "DesiredVersion": "2.9.0-111"}
2025-06-17T18:53:11.161Z INFO reconcile Resource version mismatch detected; attempting to update resource {"Kind": "open-cluster-management:console:readonly-clusterimagesets", "Name": "ClusterRoleBinding", "CurrentVersion": "2.8.2", "DesiredVersion": "2.9.0-111"}
```
https://issues.redhat.com/browse/ACM-21611
Updated release version logs during operator upgrade.
Add screenshots or GIFs that …

[ACM-21611] Fixed error in release version logs

---

pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-pod.yaml
pkg/templates/charts/toggle/cluster-backup/templates/odap-operator-pre-install-hook.yaml
pkg/templates/charts/toggle/cluster-backup/values.yaml

This PR should have been cherry picked into release 2.13
https://github.com/stolostron/multiclusterhub-operator/pull/2148/files
Checking the changes in using this PR 
Fix oadp channel default for OCP 4.19 or higher. Use OADP stable channel for this, otherwise default to the chart specified oadp channel
https://issues.redhat.com/browse/ACM-21685
Updated the oadp subscription resource to use stable channel for OCP 4.19 or higher. ( odap-operator-pre-install-hook.yaml)
Update policy validation to use stable channel for OCP 4.19 or higher (hub-backup-pod.yaml)
Tag the appropriate reviewers who should review this pull request. To add …

update oadp stable channel

---

controllers/multiclusterhub_controller.go

When a template fails to apply, the error log displays the resource details in the wrong order:
```bash
multiclusterhub_controller_test.go:2125: failed: failed to update resource Kind: flightctl-api- Name: ClusterRoleBinding: apply patches are not supported in the fake client. Follow https://github.com/kubernetes/kubernetes/issues/115598 for the current status
multiclusterhub_controller_test.go:2125: failed: failed to update resource Kind: flightctl-api- Name: ClusterRole: apply patches are not supported in the fake client. Follow https://github.com/kubernetes/kubernetes/issues/115598 for the current status
```
This PR updates the error logging to display resource information in the correct order for better clarity.
If applicable, please reference the issue(s) that this pull request …

Fixed error log for applying templates

---

config/rbac/role.yaml
pkg/templates/charts/toggle/fine-grained-rbac/templates/multicluster-role-assignment-clusterrole.yaml
pkg/templates/charts/toggle/fine-grained-rbac/templates/multicluster-role-assignment-clusterrolebinding.yaml
pkg/templates/charts/toggle/fine-grained-rbac/templates/multicluster-role-assignment-deployment.yaml
pkg/templates/charts/toggle/fine-grained-rbac/templates/multicluster-role-assignment-role.yaml
pkg/templates/charts/toggle/fine-grained-rbac/templates/multicluster-role-assignment-rolebinding.yaml
pkg/templates/charts/toggle/fine-grained-rbac/templates/multicluster-role-assignment-serviceaccount.yaml
pkg/templates/crds/multicluster-role-assignment/rbac.open-cluster-management.io_multiclusterroleassignments.yaml
pkg/templates/rbac_gen.go
pkg/utils/utils.go

In 2.15 TP, this toggle should enable the ACM console page AND install a new CRD and controller. This is the repo for the controller:
https://github.com/stolostron/multicluster-role-assignment
https://issues.redhat.com/browse/ACM-23673
Create and put the multicluster-role-assignment controller into the multiclusterhub-operator to work with the existing fine-grained-rbac-preview toggle

ACM-23673 - MulticlusterRoleAssignment - Add to installer

---

build/Dockerfile.rhtap
pkg/templates/crds/cluster-permission/rbac.open-cluster-management.io_clusterpermissions.yaml

Update the ClusterPermission CRD to pull in the latest changes.
https://issues.redhat.com/browse/ACM-22604
- Pull in the latest ClusterPermission CRD to get the new clusterRoleBindings field
- Also fixed a Konflux preflight check error by adding the LICENSE file to the multiclusterhub-operator image
n/a

ACM-22604 Update ClusterPermission CRD
